<<<<<<< HEAD:ARG_GP2016/RG3585_NUEVO_CITI/sql/06-NuevoCITI_VA.sql
=======

GO

/****** Object:  StoredProcedure [dbo].[NuevoCITI_VA]    Script Date: 21/08/2018 14:58:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON


GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[NuevoCITI_VA]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[NuevoCITI_VA]
go





>>>>>>> f0eb882f471452d1f27e630d73218029888cb36e:ARG_GP2016/RG3585_NUEVO_CITI/sql/NuevoCITI_VA.sql

/****** Object:  Stored Procedure dbo.NuevoCITI_VA    Script Date: 14/6/2015 12:34:37 PM ******/
CREATE PROCEDURE [dbo].[NuevoCITI_VA] @PERIODO CHAR(6), @REPORTE CHAR(15)
AS

CREATE TABLE #TEMPA
	(
		DOCNUMBR CHAR(21),
		RMDTYPAL SMALLINT,
		CUSTNMBR CHAR(15),
		DOCDATE datetime,
		COMPTYPE CHAR(3),
		PDV CHAR(5),
		NROCOMP CHAR(20),
		CODDOC CHAR(2),
		NROIDENT	CHAR(20),
		NOMBRE	CHAR(30),
		TOTAL	NUMERIC(19, 5),
		GRAV	NUMERIC(19, 5),
		NOGRAV	NUMERIC(19, 5),
		IVA NUMERIC(19, 5),
		EXENTO	NUMERIC(19, 5),
		PERCIVA NUMERIC(19, 5),
		PERCIIBB	NUMERIC(19, 5),
		MONEDA	CHAR(3),
		CAMBIO	NUMERIC(19, 7),
		ALICUOTAS	INT,
		CODOPER	CHAR(1),
		DUEDATE datetime
	)

CREATE TABLE #TEMP
	(
		DOCNUMBR CHAR(21),
		RMDTYPAL SMALLINT,
		CUSTNMBR CHAR(15),
		DOCDATE datetime,
		COMPTYPE CHAR(3),
		PDV CHAR(5),
		NROCOMP CHAR(20),
		CODDOC CHAR(2),
		NROIDENT	CHAR(20),
		NOMBRE	CHAR(30),
		TOTAL	NUMERIC(19, 5),
		GRAV	NUMERIC(19, 5),
		NOGRAV	NUMERIC(19, 5),
		IVA NUMERIC(19, 5),
		EXENTO	NUMERIC(19, 5),
		PERCIVA NUMERIC(19,5),
		PERCIIBB	NUMERIC(19, 5),
		MONEDA	CHAR(3),
		CAMBIO	NUMERIC(19, 7),
		ALICUOTAS	INT,
		CODOPER	CHAR(1),
		DUEDATE datetime
	)

CREATE TABLE #TEMP2
	(
		DOCNUMBR CHAR(21),
		RMDTYPAL SMALLINT,
		CUSTNMBR CHAR(15),
		COMPTYPE CHAR(3),
		PDV CHAR(5),
		NROCOMP CHAR(20),
		CODDOC CHAR(2),
		NROIDENT	CHAR(20),
		GRAVADO	NUMERIC(19, 5),
		ALICUOTA	NUMERIC(19, 5),
		IMPUESTO NUMERIC(19, 5)
	)

INSERT INTO #TEMPA
SELECT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, ISNULL(TRX.DOCDATE, CC.DOCDATE) DOCDATE, '0' + ISNULL(ISNULL(AW2.COD_COMP, AW3.COD_COMP), '00') COMTYPE, '0' + ISNULL(SUBSTRING(A.DOCNUMBR, ISNULL(AW2.Pos_PDV, AW4.Pos_PDV), 4), '0000') PDV,
'000000000000' + ISNULL(SUBSTRING(A.DOCNUMBR, ISNULL(AW2.Pos_NRO, AW4.Pos_NRO), 8), '0000') NROCOMP, 
RIGHT(ISNULL(TRX.TXRGNNUM, CM.TXRGNNUM), 2) CODCOC, RTRIM(LEFT(ISNULL(TRX.TXRGNNUM, CM.TXRGNNUM), 11)) NROIDENT,
LEFT(RTRIM(ISNULL(TRX.CUSTNAME, CM.CUSTNAME)) + REPLICATE(' ', 30), 30) NOMBRE, ISNULL(TRX.DOCAMNT, CC.ORTRXAMT) DOCAMNT,
CASE WHEN CI.ColumnaArchivo = 1 THEN TDTTXSLS ELSE 0 END GRAV,							
CASE WHEN CI.ColumnaArchivo = 4 THEN TDTTXSLS ELSE 0 END NOGRAV,						
CASE WHEN CI.ColumnaArchivo = 2 THEN A.TAXAMNT ELSE 0 END IVA,							
CASE WHEN CI.ColumnaArchivo = 3 THEN A.TAXAMNT ELSE 0 END EXENTO,						
CASE WHEN CI.ColumnaArchivo = 6 THEN A.TAXAMNT ELSE 0 END PERCIVA,						
CASE WHEN CI.ColumnaArchivo = 8 THEN A.TAXAMNT ELSE 0 END PIIBB,						
MC.CURR_CODE MONEDA, ISNULL(MC1.XCHGRATE, 1) TCAMBIO, 0 ALICUOTAS, CONVERT(VARCHAR, ISNULL(AW.OP_ORIGIN, 0)) CODOPER, CASE WHEN A.RMDTYPAL > 6 THEN CC.DOCDATE ELSE CC.DUEDATE END DUEDATE 
FROM RM10601 A
INNER JOIN RM20101 CC ON A.RMDTYPAL = CC.RMDTYPAL AND A.DOCNUMBR = CC.DOCNUMBR
LEFT OUTER JOIN SOP30200 TRX ON A.DOCNUMBR = TRX.SOPNUMBE AND CASE WHEN A.RMDTYPAL = 1 THEN 3 ELSE 4 END = TRX.SOPTYPE
INNER JOIN AWLI_RM00101 AW ON A.CUSTNMBR = AW.CUSTNMBR
LEFT OUTER JOIN AWLI40380 AW2 ON TRX.SOPTYPE = AW2.SOPTYPE AND TRX.DOCID = AW2.DOCID
CROSS JOIN AWLI40300 AW4
LEFT OUTER JOIN AWLI40370 AW3 ON A.RMDTYPAL = AW3.RMDTYPAL AND 2 = AW3.TipoReporte AND SUBSTRING(A.DOCNUMBR, ISNULL(AW2.Pos_Letra, AW4.Pos_Letra), 1) = CASE AW3.LETRA WHEN 1 THEN 'A' WHEN 2 THEN 'B' WHEN 4 THEN 'E' END
INNER JOIN RM00101 CM ON A.CUSTNMBR = CM.CUSTNMBR
INNER JOIN DYNAMICS..AWLI_MC40200 MC ON ISNULL(TRX.CURNCYID, CC.CURNCYID) = MC.CURNCYID
INNER JOIN
(SELECT A.RPTID, A.DSCRIPTN, A.NRORDCOL, A.IDTAXOP, B.TAXDTLID, C.TXDTLDSC FROM AWLI40004 A INNER JOIN AWLI40102 B ON A.IDTAXOP = B.IDTAXOP
INNER JOIN TX00201 C ON B.TAXDTLID = C.TAXDTLID
where rptid IN(@REPORTE)	 ) TX ON A.TAXDTLID = TX.TAXDTLID
INNER JOIN tblColumnasIVA CI ON TX.RPTID = CI.RPTID AND TX.NRORDCOL = CI.NRORDCOL
INNER JOIN TX00201 B ON TX.TAXDTLID = B.TAXDTLID
LEFT OUTER JOIN MC020102 MC1 ON A.DOCNUMBR = MC1.DOCNUMBR AND A.RMDTYPAL = MC1.RMDTYPAL AND A.CUSTNMBR = MC1.CUSTNMBR
WHERE ISNULL(TRX.VOIDSTTS, CC.VOIDSTTS) = 0 and left(CONVERT(char(8), ISNULL(TRX.DOCDATE, CC.DOCDATE), 112), 6) = @PERIODO AND CI.TipoReporte = 2

INSERT INTO #TEMPA
SELECT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, ISNULL(TRX.DOCDATE, CC.DOCDATE) DOCDATE, '0' + ISNULL(ISNULL(AW2.COD_COMP, AW3.COD_COMP), '00') COMTYPE, '0' + ISNULL(SUBSTRING(A.DOCNUMBR, ISNULL(AW2.Pos_PDV, AW4.Pos_PDV), 4), '0000') PDV,
'000000000000' + ISNULL(SUBSTRING(A.DOCNUMBR, ISNULL(AW2.Pos_NRO, AW4.Pos_NRO), 8), '0000') NROCOMP, 
RIGHT(ISNULL(TRX.TXRGNNUM, CM.TXRGNNUM), 2) CODCOC, RTRIM(LEFT(ISNULL(TRX.TXRGNNUM, CM.TXRGNNUM), 11)) NROIDENT,
LEFT(RTRIM(ISNULL(TRX.CUSTNAME, CM.CUSTNAME)) + REPLICATE(' ', 30), 30) NOMBRE, ISNULL(TRX.DOCAMNT, CC.ORTRXAMT) DOCAMNT,
CASE WHEN CI.ColumnaArchivo = 1 THEN TDTTXSLS ELSE 0 END GRAV,							
CASE WHEN CI.ColumnaArchivo = 4 THEN TDTTXSLS ELSE 0 END NOGRAV,						
CASE WHEN CI.ColumnaArchivo = 2 THEN A.TAXAMNT ELSE 0 END IVA,							
CASE WHEN CI.ColumnaArchivo = 3 THEN A.TAXAMNT ELSE 0 END EXENTO,						
CASE WHEN CI.ColumnaArchivo = 6 THEN A.TAXAMNT ELSE 0 END PERCIVA,						
CASE WHEN CI.ColumnaArchivo = 8 THEN A.TAXAMNT ELSE 0 END PIIBB,						
MC.CURR_CODE MONEDA, ISNULL(MC1.XCHGRATE, 1) TCAMBIO, 0 ALICUOTAS, CONVERT(VARCHAR, ISNULL(AW.OP_ORIGIN, 0)) CODOPER, CASE WHEN A.RMDTYPAL > 6 THEN CC.DOCDATE ELSE CC.DUEDATE END DUEDATE 
FROM RM30601 A
INNER JOIN RM30101 CC ON A.RMDTYPAL = CC.RMDTYPAL AND A.DOCNUMBR = CC.DOCNUMBR
LEFT OUTER JOIN SOP30200 TRX ON A.DOCNUMBR = TRX.SOPNUMBE AND CASE WHEN A.RMDTYPAL = 1 THEN 3 ELSE 4 END = TRX.SOPTYPE
INNER JOIN AWLI_RM00101 AW ON A.CUSTNMBR = AW.CUSTNMBR
LEFT OUTER JOIN AWLI40380 AW2 ON TRX.SOPTYPE = AW2.SOPTYPE AND TRX.DOCID = AW2.DOCID
CROSS JOIN AWLI40300 AW4
LEFT OUTER JOIN AWLI40370 AW3 ON A.RMDTYPAL = AW3.RMDTYPAL AND 2 = AW3.TipoReporte AND SUBSTRING(A.DOCNUMBR, ISNULL(AW2.Pos_Letra, AW4.Pos_Letra), 1) = CASE AW3.LETRA WHEN 1 THEN 'A' WHEN 2 THEN 'B' WHEN 4 THEN 'E' END 
INNER JOIN RM00101 CM ON A.CUSTNMBR = CM.CUSTNMBR
INNER JOIN DYNAMICS..AWLI_MC40200 MC ON ISNULL(TRX.CURNCYID, CC.CURNCYID) = MC.CURNCYID
INNER JOIN
(SELECT A.RPTID, A.DSCRIPTN, A.NRORDCOL, A.IDTAXOP, B.TAXDTLID, C.TXDTLDSC FROM AWLI40004 A INNER JOIN AWLI40102 B ON A.IDTAXOP = B.IDTAXOP
INNER JOIN TX00201 C ON B.TAXDTLID = C.TAXDTLID
where rptid IN(@REPORTE)	 ) TX ON A.TAXDTLID = TX.TAXDTLID
INNER JOIN tblColumnasIVA CI ON TX.RPTID = CI.RPTID AND TX.NRORDCOL = CI.NRORDCOL
INNER JOIN TX00201 B ON TX.TAXDTLID = B.TAXDTLID
LEFT OUTER JOIN MC020102 MC1 ON A.DOCNUMBR = MC1.DOCNUMBR AND A.RMDTYPAL = MC1.RMDTYPAL AND A.CUSTNMBR = MC1.CUSTNMBR
WHERE ISNULL(TRX.VOIDSTTS, CC.VOIDSTTS) = 0 and left(CONVERT(char(8), ISNULL(TRX.DOCDATE, CC.DOCDATE), 112), 6) = @PERIODO AND CI.TipoReporte = 2

INSERT INTO #TEMP
SELECT 		DOCNUMBR,
		RMDTYPAL,
		CUSTNMBR,
		DOCDATE,
		COMPTYPE,
		PDV,
		NROCOMP,
		CODDOC,
		NROIDENT,
		NOMBRE,
		TOTAL,
		SUM(GRAV) GRAV,
		SUM(NOGRAV) NOGRAV,
		SUM(IVA) IVA,
		SUM(EXENTO) EXENTO,
		SUM(PERCIVA) PERCIVA,
		SUM(PERCIIBB) PERCIIBB,
		MONEDA,
		CAMBIO,
		ALICUOTAS,
		CODOPER,
		DUEDATE
FROM #TEMPA
GROUP BY 	DOCNUMBR,
		RMDTYPAL,
		CUSTNMBR,
		DOCDATE,
		COMPTYPE,
		PDV,
		NROCOMP,
		CODDOC,
		NROIDENT,
		NOMBRE,
		TOTAL,
		MONEDA,
		CAMBIO,
		ALICUOTAS,
		CODOPER,
		DUEDATE

UPDATE #TEMP
SET ALICUOTAS = TX.ALICUOTAS
FROM #TEMP A
INNER JOIN (
SELECT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, COUNT(A.ALICUOTAS) ALICUOTAS FROM
(SELECT DISTINCT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, B.TXDTLPCT ALICUOTAS FROM RM10601 A INNER JOIN
(SELECT A.RPTID, A.DSCRIPTN, A.NRORDCOL, A.IDTAXOP, B.TAXDTLID, C.TXDTLDSC, CI.ColumnaArchivo FROM AWLI40004 A INNER JOIN AWLI40102 B ON A.IDTAXOP = B.IDTAXOP
INNER JOIN tblColumnasIVA CI ON A.RPTID = CI.RPTID AND A.NRORDCOL = CI.NRORDCOL
INNER JOIN TX00201 C ON B.TAXDTLID = C.TAXDTLID
where A.rptid IN(@REPORTE) AND CI.TipoReporte = 2 AND CI.ColumnaArchivo = 2 ) TX ON A.TAXDTLID = TX.TAXDTLID
INNER JOIN TX00201 B ON TX.TAXDTLID = B.TAXDTLID
WHERE TX.ColumnaArchivo = 2 AND A.TAXAMNT <> 0) A 
GROUP BY A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR ) TX
ON A.DOCNUMBR = TX.DOCNUMBR AND A.RMDTYPAL = TX.RMDTYPAL AND A.CUSTNMBR = TX.CUSTNMBR

UPDATE #TEMP
SET ALICUOTAS = TX.ALICUOTAS
FROM #TEMP A
INNER JOIN (
SELECT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, COUNT(A.ALICUOTAS) ALICUOTAS FROM
(SELECT DISTINCT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, B.TXDTLPCT ALICUOTAS FROM RM30601 A INNER JOIN
(SELECT A.RPTID, A.DSCRIPTN, A.NRORDCOL, A.IDTAXOP, B.TAXDTLID, C.TXDTLDSC, CI.ColumnaArchivo FROM AWLI40004 A INNER JOIN AWLI40102 B ON A.IDTAXOP = B.IDTAXOP
INNER JOIN tblColumnasIVA CI ON A.RPTID = CI.RPTID AND A.NRORDCOL = CI.NRORDCOL
INNER JOIN TX00201 C ON B.TAXDTLID = C.TAXDTLID
where A.rptid IN(@REPORTE) AND CI.TipoReporte = 2 AND CI.ColumnaArchivo = 2 ) TX ON A.TAXDTLID = TX.TAXDTLID
INNER JOIN TX00201 B ON TX.TAXDTLID = B.TAXDTLID
WHERE TX.ColumnaArchivo = 2 AND A.TAXAMNT <> 0) A 
GROUP BY A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR ) TX
ON A.DOCNUMBR = TX.DOCNUMBR AND A.RMDTYPAL = TX.RMDTYPAL AND A.CUSTNMBR = TX.CUSTNMBR

INSERT INTO #TEMP2
SELECT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, A.COMPTYPE, A.PDV, A.NROCOMP, A.CODDOC, A.NROIDENT,
SUM(B.TDTTXSLS) GRAVADO, TX.TXDTLPCT, SUM(B.TAXAMNT) IMPUESTO
FROM #TEMP A INNER JOIN RM10601 B ON A.DOCNUMBR = B.DOCNUMBR AND A.RMDTYPAL = B.RMDTYPAL AND A.CUSTNMBR = B.CUSTNMBR
INNER JOIN 
(SELECT A.RPTID, A.DSCRIPTN, A.NRORDCOL, A.IDTAXOP, B.TAXDTLID, C.TXDTLPCT, CI.ColumnaArchivo FROM AWLI40004 A INNER JOIN AWLI40102 B ON A.IDTAXOP = B.IDTAXOP
INNER JOIN tblColumnasIVA CI ON A.RPTID = CI.RPTID AND A.NRORDCOL = CI.NRORDCOL
INNER JOIN TX00201 C ON B.TAXDTLID = C.TAXDTLID
where A.rptid IN(@REPORTE)	 AND CI.TipoReporte = 2 AND CI.ColumnaArchivo = 2 ) TX ON B.TAXDTLID = TX.TAXDTLID
WHERE TX.ColumnaArchivo = 2 AND B.TAXAMNT <> 0
GROUP BY A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, A.COMPTYPE, A.PDV, A.NROCOMP, A.CODDOC, A.NROIDENT, TX.TXDTLPCT

INSERT INTO #TEMP2
SELECT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, A.COMPTYPE, A.PDV, A.NROCOMP, A.CODDOC, A.NROIDENT,
SUM(B.TDTTXSLS) GRAVADO, TX.TXDTLPCT, SUM(B.TAXAMNT) IMPUESTO
FROM #TEMP A INNER JOIN RM30601 B ON A.DOCNUMBR = B.DOCNUMBR AND A.RMDTYPAL = B.RMDTYPAL AND A.CUSTNMBR = B.CUSTNMBR
INNER JOIN 
(SELECT A.RPTID, A.DSCRIPTN, A.NRORDCOL, A.IDTAXOP, B.TAXDTLID, C.TXDTLPCT, CI.ColumnaArchivo FROM AWLI40004 A INNER JOIN AWLI40102 B ON A.IDTAXOP = B.IDTAXOP
INNER JOIN tblColumnasIVA CI ON A.RPTID = CI.RPTID AND A.NRORDCOL = CI.NRORDCOL
INNER JOIN TX00201 C ON B.TAXDTLID = C.TAXDTLID
where A.rptid IN(@REPORTE)	 AND CI.ColumnaArchivo = 2 AND CI.ColumnaArchivo = 2 ) TX ON B.TAXDTLID = TX.TAXDTLID
WHERE TX.ColumnaArchivo = 2 AND B.TAXAMNT <> 0
GROUP BY A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, A.COMPTYPE, A.PDV, A.NROCOMP, A.CODDOC, A.NROIDENT, TX.TXDTLPCT

INSERT INTO #TEMP2
SELECT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, A.COMPTYPE, A.PDV, A.NROCOMP, A.CODDOC, A.NROIDENT,
0 GRAVADO, 0 TXDTLPCT, 0 IMPUESTO
FROM #TEMP A INNER JOIN RM20101 B ON A.DOCNUMBR = B.DOCNUMBR AND A.RMDTYPAL = B.RMDTYPAL AND A.CUSTNMBR = B.CUSTNMBR
LEFT OUTER JOIN #TEMP2 C ON A.DOCNUMBR = C.DOCNUMBR AND A.RMDTYPAL = C.RMDTYPAL AND A.CUSTNMBR = C.CUSTNMBR
WHERE A.ALICUOTAS = 0 AND (C.DOCNUMBR IS NULL  OR ISNULL(C.IMPUESTO, 0)=0)
 
INSERT INTO #TEMP2
SELECT A.DOCNUMBR, A.RMDTYPAL, A.CUSTNMBR, A.COMPTYPE, A.PDV, A.NROCOMP, A.CODDOC, A.NROIDENT,
0 GRAVADO, 0 TXDTLPCT, 0 IMPUESTO
FROM #TEMP A INNER JOIN RM30101 B ON A.DOCNUMBR = B.DOCNUMBR AND A.RMDTYPAL = B.RMDTYPAL AND A.CUSTNMBR = B.CUSTNMBR
LEFT OUTER JOIN #TEMP2 C ON A.DOCNUMBR = C.DOCNUMBR AND A.RMDTYPAL = C.RMDTYPAL AND A.CUSTNMBR = C.CUSTNMBR
WHERE A.ALICUOTAS = 0 AND (C.DOCNUMBR IS NULL  OR ISNULL(C.IMPUESTO, 0)=0)
 
SELECT 
RTRIM(COMPTYPE)		+ -- TIPO DE COMPROBANTE
RTRIM(PDV)			+ -- PUNTO DE VENTA
RTRIM(NROCOMP)		+ -- NRO COMPROBANTE
RIGHT(REPLACE('000000000000000' + LEFT(CONVERT(VARCHAR, GRAVADO), LEN(CONVERT(VARCHAR, GRAVADO))-3), '.', ''), 15)    + -- GRAV
CASE ALICUOTA WHEN 10.5 THEN '0004' WHEN 21 THEN '0005' WHEN 27 THEN '0006' WHEN 5 THEN '0008' wHEN 2.5 THEN '0009' ELSE '0003' END		+ -- ALICUOTA
RIGHT(REPLACE('000000000000000' + LEFT(CONVERT(VARCHAR, IMPUESTO), LEN(CONVERT(VARCHAR, IMPUESTO))-3), '.', ''), 15)   TEXTO -- IMPUESTO
FROM #TEMP2 WHERE dbo.fncESNUMERICO(PDV) = 1
ORDER BY PDV, COMPTYPE, NROCOMP



