/*Count : 15 */
 
set DATEFORMAT ymd 
GO 

/*Begin_mcpReceiptsBatchView*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[mcpReceiptsBatchView]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[mcpReceiptsBatchView]
GO

CREATE VIEW dbo.mcpReceiptsBatchView AS 
SELECT ISNULL(KM.TRXSORCE, '') AS TRXSORCE, RECIBOS.BCHSOURC, RECIBOS.BACHNUMB, RECIBOS.DOCDATE, RECIBOS.MCPTYPID, RECIBOS.NUMBERIE, RECIBOS.RMDTYPAL AS DOCTYPE, C.DOCDESCR, RECIBOS.NFENTID,  
  RECIBOS.CURNCYID AS CURNCYIDREC, ISNULL(MC.CURRNIDX, 0) AS CURRNIDXREC, ISNULL(MC.ORORGTRX, RECIBOS.TOTAMNT) AS IMPORTEORIGINAL, RECIBOS.TOTAMNT, RECIBOS.GLPOSTDT, RECIBOS.VOIDSTTS, 
  CASE KM.TRXSORCE WHEN '' THEN 0 ELSE 1 END AS CONTABILIZADO 
FROM   (SELECT CW.BCHSOURC, CW.BACHNUMB, CW.DOCDATE, CW.MCPTYPID, CW.NUMBERIE, CW.RMDTYPAL, CW.NFENTID, CW.CURNCYID, CW.TOTAMNT, CW.GLPOSTDT, 0 AS VOIDSTTS 
   FROM nfMCP10000 CW 
   ) RECIBOS 
LEFT JOIN MC020102 MC ON MC.DOCNUMBR = RECIBOS.NUMBERIE 
       AND MC.RMDTYPAL = RECIBOS.RMDTYPAL 
LEFT JOIN RM00401 KM ON KM.CUSTNMBR = RECIBOS.NFENTID 
      AND KM.RMDTYPAL = RECIBOS.RMDTYPAL 
      AND KM.DOCNUMBR = RECIBOS.NUMBERIE 
      AND KM.BCHSOURC = RECIBOS.BCHSOURC 
INNER JOIN RM40401 C ON C.RMDTYPAL = RECIBOS.RMDTYPAL 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[mcpReceiptsBatchView]  TO [DYNGRP] 
GO 

/*End_mcpReceiptsBatchView*/ 
/*Begin_mcpBatchControlView*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[mcpBatchControlView]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[mcpBatchControlView]
GO

CREATE VIEW dbo.mcpBatchControlView AS 
SELECT RECIBOS.TRXSORCE, RECIBOS.BCHSOURC, RECIBOS.BACHNUMB, RECIBOS.DOCDATE, RECIBOS.GLPOSTDT, RECIBOS.MCPTYPID, RECIBOS.NUMBERIE, RECIBOS.DOCTYPE, RECIBOS.DOCDESCR, RECIBOS.NFENTID, 
  RECIBOS.CURNCYIDREC, RECIBOS.CURRNIDXREC, IMPORTEORIGINAL, RECIBOS.TOTAMNT, 
  LINEAS.LNSEQNBR, LINEAS.MEDIOID, MEDIOS.DSCRIPTN AS DESCMEDIO, LINEAS.CURNCYID, LINEAS.CURRNIDX, LINEAS.MONTO, LINEAS.MONTOFUNCIONAL, LINEAS.DUEDATE, LINEAS.BANKID 
FROM   mcpReceiptsBatchView RECIBOS 
INNER JOIN (SELECT CASH.MCPTYPID, CASH.NUMBERIE, CASH.LNSEQNBR, ISNULL(MCL.MEDIOID, CASH.MEDIOID) AS MEDIOID, 
      CASH.AMOUNTO AS MONTO, 
     CASH.LINEAMNT AS MONTOFUNCIONAL, 
     ISNULL(MCL.CURNCYID, CASH.CURNCYID) AS CURNCYID, 
     ISNULL(MCL.CURRNIDX, CASH.CURRNIDX) AS CURRNIDX, 
     CASH.DUEDATE, CASH.BANKID 
    FROM (SELECT CLW.MCPTYPID, CLW.NUMBERIE, CLW.LNSEQNBR, CLW.MEDIOID, CLW.LINEAMNT, CLW.CURNCYID, CLW.CURRNIDX, CLW.DUEDATE, CLW.BANKID, CLW.AMOUNTO 
       FROM   nfMCP10100 CLW 
       UNION 
       SELECT CL.MCPTYPID, CL.NUMBERIE, CL.LNSEQNBR, CL.MEDIOID, CL.LINEAMNT, CL.CURNCYID, CL.CURRNIDX, CL.DUEDATE, CL.BANKID, CL.AMOUNTO 
       FROM   nfMCP20100 CL) CASH 
       LEFT JOIN TII_MC_RM10100 MCL ON CASH.MCPTYPID = MCL.MCPTYPID 
              AND CASH.NUMBERIE = MCL.NUMBERIE 
              AND CASH.LNSEQNBR = MCL.LNSEQNBR 
              AND CASH.MEDIOID = MCL.MEDIOID 
LEFT JOIN (SELECT CAR.MEDIOID, CAR.LNSEQNBR, CAR.INGTYPE AS MCPTYPID, CAR.INGNUMB AS NUMBERIE, CAR.EGRTYPE, CAR.EGRNUMB 
   FROM   nfMCP10200 CAR 
   WHERE CAR.CARTSTAT <> 4 
     AND CAR.CARTSTAT <> 6 
     AND CAR.CARTSTAT <> 7) CARTERA ON CARTERA.MEDIOID = CASH.MEDIOID 
           AND CARTERA.LNSEQNBR = CASH.LNSEQNBR 
           AND CARTERA.MCPTYPID = CASH.MCPTYPID 
           AND CARTERA.NUMBERIE = CASH.NUMBERIE) LINEAS ON LINEAS.MCPTYPID = RECIBOS.MCPTYPID 
                      AND LINEAS.NUMBERIE = RECIBOS.NUMBERIE 
INNER JOIN nfMCP00700 MEDIOS ON MEDIOS.MEDIOID = LINEAS.MEDIOID 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[mcpBatchControlView]  TO [DYNGRP] 
GO 

/*End_mcpBatchControlView*/
/*Begin_mcpPaymentsBatchView*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[mcpPaymentsBatchView]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[mcpPaymentsBatchView]
GO

CREATE VIEW dbo.mcpPaymentsBatchView AS 
SELECT ISNULL(KM.TRXSORCE, '') AS TRXSORCE, PMNTS.BCHSOURC, PMNTS.BACHNUMB, PMNTS.DOCDATE, PMNTS.MCPTYPID, PMNTS.NUMBERIE, PMNTS.DOCTYPE AS DOCTYPE, C.DOCTYNAM, PMNTS.NFENTID,  
  PMNTS.CURNCYID AS CURNCYIDREC, ISNULL(MC.CURRNIDX, 0) AS CURRNIDXREC, ISNULL(MC.ORDOCAMT, PMNTS.DOCAMNT) AS IMPORTEORIGINAL, PMNTS.DOCAMNT, PMNTS.PSTGDATE, PMNTS.VOIDSTTS, 
  CASE KM.TRXSORCE WHEN '' THEN 0 ELSE 1 END AS CONTABILIZADO 
FROM   (SELECT CW.BCHSOURC, CW.BACHNUMB, CW.DOCDATE, CW.MCPTYPID, CW.NUMBERIE, CW.DOCTYPE, CW.NFENTID, CW.CURNCYID, CW.DOCAMNT, CW.PSTGDATE, 0 AS VOIDSTTS 
   FROM nfMCP_PM10000 CW 
    ) PMNTS 
LEFT JOIN MC020103 MC ON MC.VCHRNMBR = PMNTS.NUMBERIE 
       AND MC.DOCTYPE = PMNTS.DOCTYPE 
LEFT JOIN PM00400 KM ON KM.VENDORID = PMNTS.NFENTID 
      AND KM.DOCTYPE = PMNTS.DOCTYPE 
      AND KM.DOCNUMBR = PMNTS.NUMBERIE 
      AND KM.BCHSOURC = PMNTS.BCHSOURC 
INNER JOIN PM40102 C ON C.DOCTYPE = PMNTS.DOCTYPE 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[mcpPaymentsBatchView]  TO [DYNGRP] 
GO 

/*End_mcpPaymentsBatchView*/
/*Begin_mcpPMBalanceVIEW*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[mcpPMBalanceVIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[mcpPMBalanceVIEW]
GO

CREATE VIEW dbo.mcpPMBalanceVIEW AS
SELECT  A.VENDORID, A.DOCNUMBR, A.DOCTYPE, C.DOCTYNAM, A.DOCDATE, A.VCHRNMBR,  A.OrCurIdx, A.ORDOCAMT,
SALDO = CASE
WHEN A.DOCTYPE < 4 THEN MONTO
WHEN A.DOCTYPE >= 4 THEN (-1) * MONTO
END
FROM   (SELECT VENDORID, DOCNUMBR, DOCTYPE, DOCDATE, VCHRNMBR, 
(SELECT CURRNIDX FROM MC020103 WHERE VENDORID = PM20000.VENDORID AND VCHRNMBR= PM20000.VCHRNMBR) OrCurIdx, 
(SELECT ORDOCAMT FROM MC020103 WHERE VENDORID = PM20000.VENDORID AND VCHRNMBR = PM20000.VCHRNMBR) ORDOCAMT,DOCAMNT AS MONTO 
FROM PM20000 
WHERE VOIDED = 0 
UNION 
SELECT VENDORID, DOCNUMBR, DOCTYPE, DOCDATE, VCHRNMBR, (SELECT CURRNIDX FROM MC020103 WHERE VENDORID = PM30200.VENDORID AND VCHRNMBR = PM30200.VCHRNMBR) OrCurIdx, 
(SELECT ORDOCAMT FROM MC020103 WHERE VENDORID = PM30200.VENDORID AND VCHRNMBR = PM30200.VCHRNMBR) ORDOCAMT,DOCAMNT AS MONTO 
FROM PM30200 
WHERE VOIDED = 0) A 
INNER JOIN PM00200 B ON B.VENDORID = A.VENDORID
INNER JOIN PM40102 C ON C.DOCTYPE = A.DOCTYPE
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[mcpPMBalanceVIEW]  TO [DYNGRP] 
GO 

/*End_mcpPMBalanceVIEW*/
/*Begin_mcpPMBatchControlView*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[mcpPMBatchControlView]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[mcpPMBatchControlView]
GO

CREATE VIEW dbo.mcpPMBatchControlView AS 
SELECT PMNTS.TRXSORCE, PMNTS.BCHSOURC, PMNTS.BACHNUMB, PMNTS.DOCDATE, PMNTS.PSTGDATE, PMNTS.MCPTYPID, PMNTS.NUMBERIE, PMNTS.DOCTYPE, PMNTS.DOCTYNAM, PMNTS.NFENTID, 
  PMNTS.CURNCYIDREC, PMNTS.CURRNIDXREC, IMPORTEORIGINAL, PMNTS.DOCAMNT, 
  LINEAS.LNSEQNBR, LINEAS.MEDIOID, MEDIOS.DSCRIPTN AS DESCMEDIO, LINEAS.CURNCYID, LINEAS.CURRNIDX, LINEAS.MONTO, LINEAS.MONTOFUNCIONAL, LINEAS.DUEDATE, LINEAS.BANKID 
FROM   mcpPaymentsBatchView PMNTS 
INNER JOIN (SELECT CASH.MCPTYPID, CASH.NUMBERIE, CASH.LNSEQNBR, ISNULL(MCL.MEDIOID, CASH.MEDIOID) AS MEDIOID, 
      CASH.AMOUNTO AS MONTO, 
     CASH.LINEAMNT AS MONTOFUNCIONAL, 
     ISNULL(MCL.CURNCYID, CASH.CURNCYID) AS CURNCYID, 
     ISNULL(MCL.CURRNIDX, CASH.CURRNIDX) AS CURRNIDX, 
     CASH.DUEDATE, CASH.BANKID 
    FROM (SELECT CLW.MCPTYPID, CLW.NUMBERIE, CLW.LNSEQNBR, CLW.MEDIOID, CLW.LINEAMNT, CLW.CURNCYID, CLW.CURRNIDX, CLW.DUEDATE, CLW.BANKID ,CLW.AMOUNTO 
       FROM   nfMCP_PM10100 CLW 
       UNION 
       SELECT CL.MCPTYPID, CL.NUMBERIE, CL.LNSEQNBR, CL.MEDIOID, CL.LINEAMNT, CL.CURNCYID, CL.CURRNIDX, CL.DUEDATE, CL.BANKID ,CL.AMOUNTO 
       FROM   nfMCP_PM20100 CL) CASH 
       LEFT JOIN TII_MC_PM10100 MCL ON CASH.MCPTYPID = MCL.MCPTYPID 
              AND CASH.NUMBERIE = MCL.NUMBERIE 
              AND CASH.LNSEQNBR = MCL.LNSEQNBR 
              AND CASH.MEDIOID = MCL.MEDIOID 
LEFT JOIN (SELECT CAR.MEDIOID, CAR.LNSEQNBR, CAR.INGTYPE AS MCPTYPID, CAR.INGNUMB AS NUMBERIE, CAR.EGRTYPE, CAR.EGRNUMB 
   FROM   nfMCP10200 CAR 
   WHERE CAR.CARTSTAT <> 4 
     AND CAR.CARTSTAT <> 6 
     AND CAR.CARTSTAT <> 7) CARTERA ON CARTERA.MEDIOID = CASH.MEDIOID 
           AND CARTERA.LNSEQNBR = CASH.LNSEQNBR 
           AND CARTERA.MCPTYPID = CASH.MCPTYPID 
           AND CARTERA.NUMBERIE = CASH.NUMBERIE) LINEAS ON LINEAS.MCPTYPID = PMNTS.MCPTYPID 
                      AND LINEAS.NUMBERIE = PMNTS.NUMBERIE 
INNER JOIN nfMCP00700 MEDIOS ON MEDIOS.MEDIOID = LINEAS.MEDIOID 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[mcpPMBatchControlView]  TO [DYNGRP] 
GO 

/*End_mcpPMBatchControlView*/
/*Begin_mcpRMBalanceVIEW*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[mcpRMBalanceVIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[mcpRMBalanceVIEW]
GO

CREATE VIEW dbo.mcpRMBalanceVIEW AS
SELECT  A.CUSTNMBR, A.DOCNUMBR, A.RMDTYPAL, C.DOCDESCR, A.DOCDATE, 
   SALDO = CASE 
     WHEN A.RMDTYPAL < 7 and A.RMDTYPAL <> 2 THEN MONTO 
     WHEN A.RMDTYPAL >= 7 THEN (-1) * MONTO 
     END 
FROM   (SELECT CUSTNMBR, DOCNUMBR, RMDTYPAL, DOCDATE, ORTRXAMT AS MONTO 
   FROM RM20101 
   WHERE VOIDSTTS = 0 AND RMDTYPAL not in (2,6) AND BCHSOURC <> 'XRM_SCH_POSTING'
   UNION 
   SELECT CUSTNMBR, DOCNUMBR, RMDTYPAL, DOCDATE, ORTRXAMT AS MONTO 
   FROM RM30101 
   WHERE VOIDSTTS = 0 AND RMDTYPAL not in (2,6)) A 
INNER JOIN RM00101 B ON B.CUSTNMBR = A.CUSTNMBR
INNER JOIN RM40401 C ON C.RMDTYPAL = A.RMDTYPAL
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[mcpRMBalanceVIEW]  TO [DYNGRP] 
GO

/*End_mcpRMBalanceVIEW*/
/*Begin_nfMCP_PM_ALL_Applied*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfMCP_PM_ALL_Applied]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfMCP_PM_ALL_Applied]
GO

CREATE VIEW dbo.nfMCP_PM_ALL_Applied 
AS 
SELECT * FROM (SELECT FAA.VENDORID, FAA.VCHRNMBR AS VCHRNMBR, FAA.DOCTYPE AS DOCTYPE, 
FAA.APTVCHNM AS APTVCHNM, FAA.APTODCTY AS APTODCTY, FAA.APPLDAMT AS APPLDAMT, 
FAA.RLGANLOS, dbo.PM00400.DOCNUMBR AS DOCNUMBR, dbo.PM00400.DUEDATE AS DUEDATE, 
FTT.DOCAMNT FROM ((SELECT dbo.PM20000.VENDORID, dbo.PM20000.VCHRNMBR, 
dbo.PM20000.DOCTYPE, dbo.PM10200.APTVCHNM, dbo.PM10200.APTODCTY, dbo.PM10200.APPLDAMT, 
dbo.PM10200.RLGANLOS FROM dbo.PM20000 INNER JOIN dbo.PM10200 
ON dbo.PM20000.VCHRNMBR = dbo.PM10200.VCHRNMBR AND dbo.PM20000.DOCTYPE = 
dbo.PM10200.DOCTYPE WHERE (dbo.PM20000.DOCTYPE = 6)) FAA INNER JOIN 
dbo.PM00400 ON FAA.APTVCHNM = dbo.PM00400.CNTRLNUM AND 
FAA.APTODCTY = dbo.PM00400.DOCTYPE) LEFT OUTER JOIN 
(SELECT * FROM (SELECT * FROM (select VENDORID, VCHRNMBR, DOCTYPE, DOCAMNT FROM 
dbo.PM20000) FA UNION SELECT * FROM (select VENDORID, VCHRNMBR, DOCTYPE, DOCAMNT FROM 
dbo.PM30200) FH) FT) FTT 
ON dbo.PM00400.CNTRLNUM = FTT.VCHRNMBR AND dbo.PM00400.DOCTYPE = FTT.DOCTYPE 
WHERE NOT FTT.DOCAMNT IS NULL 
UNION 
SELECT FAH.VENDORID, FAH.VCHRNMBR AS VCHRNMBR, FAH.DOCTYPE AS DOCTYPE, 
FAH.APTVCHNM AS APTVCHNM, FAH.APTODCTY AS APTODCTY, FAH.APPLDAMT AS APPLDAMT, 
FAH.RLGANLOS, dbo.PM00400.DOCNUMBR AS DOCNUMBR, dbo.PM00400.DUEDATE AS DUEDATE, 
FTT.DOCAMNT FROM ((SELECT dbo.PM30200.VENDORID, dbo.PM30200.VCHRNMBR, 
dbo.PM30200.DOCTYPE, dbo.PM30300.APTVCHNM, dbo.PM30300.APTODCTY, dbo.PM30300.APPLDAMT, 
dbo.PM30300.RLGANLOS FROM dbo.PM30200 INNER JOIN dbo.PM30300 
ON dbo.PM30200.VCHRNMBR = dbo.PM30300.VCHRNMBR AND dbo.PM30200.DOCTYPE = 
dbo.PM30300.DOCTYPE WHERE (dbo.PM30200.DOCTYPE = 6)) FAH INNER JOIN 
dbo.PM00400 ON FAH.APTVCHNM = dbo.PM00400.CNTRLNUM AND 
FAH.APTODCTY = dbo.PM00400.DOCTYPE) LEFT OUTER JOIN 
(SELECT * FROM (SELECT * FROM (select VENDORID, VCHRNMBR, DOCTYPE, DOCAMNT FROM 
dbo.PM20000) FA UNION SELECT * FROM (select VENDORID, VCHRNMBR, DOCTYPE, DOCAMNT FROM 
dbo.PM30200) FH) FT) FTT 
ON dbo.PM00400.CNTRLNUM = FTT.VCHRNMBR AND dbo.PM00400.DOCTYPE = FTT.DOCTYPE 
WHERE NOT FTT.DOCAMNT IS NULL) AA
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfMCP_PM_ALL_Applied]  TO [DYNGRP] 
GO 

/*End_nfMCP_PM_ALL_Applied*/
/*Begin_nfRET_Invoices*/

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfRET_Invoices]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfRET_Invoices]
GO

Create VIEW nfRET_Invoices as
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM20000.CURNCYID,TAXSCHID, DSTINDX,(CRDTAMNT+DEBITAMT)-isnull(APPAMT,0) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID
from PM20000 inner join PM10100 on PM20000.VCHRNMBR = PM10100.VCHRNMBR and PM20000.VENDORID = PM10100.VENDORID 
inner join nfRET_GL00101 on PM10100.DSTINDX = nfRET_GL00101.ACTINDX
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where DOCTYPE in (1,2,3) and DISTTYPE in (5,6) and VOIDED = 0 and BCHSOURC <> 'Rcvg Trx Ivc'
UNION ALL
SELECT PM30200.VCHRNMBR,PM30200.VENDORID,PM30200.DOCTYPE,PM30200.DOCDATE,PM30200.POSTEDDT,PM30200.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM30200.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM30200.CURNCYID,TAXSCHID, DSTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID
from PM30200 inner join PM30600 on PM30200.VCHRNMBR = PM30600.VCHRNMBR and PM30200.VENDORID = PM30600.VENDORID  and PM30200.DOCTYPE = PM30600.DOCTYPE
inner join nfRET_GL00101 on PM30600.DSTINDX = nfRET_GL00101.ACTINDX
where PM30200.DOCTYPE in (1,2,3) and DISTTYPE in (5,6) and VOIDED = 0 and BCHSOURC <> 'Rcvg Trx Ivc'
UNION ALL
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM20000.CURNCYID,TAXSCHID,TEMPSHIPINC.ACTINDX,PRCHAMNT-isnull(APPAMT,0) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID
from PM20000 
inner join (select distinct VNDDOCNM,VCHRNMBR,POP30300.VENDORID,POP30390.ACTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID from POP30300 
inner join POP10600 on POP30300.POPRCTNM = POP10600.POPIVCNO
inner join POP30390 on POP10600.POPRCTNM = POP30390.POPRCTNM and POP30390.VENDORID = POP30300.VENDORID 
and DISTTYPE = 1 inner join nfRET_GL00101 on POP30390.ACTINDX = nfRET_GL00101.ACTINDX) TEMPSHIPINC on PM20000.VCHRNMBR = TEMPSHIPINC.VCHRNMBR and PM20000.VENDORID = TEMPSHIPINC.VENDORID 
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where DOCTYPE in (1,2,3)  and VOIDED = 0 and BCHSOURC = 'Rcvg Trx Ivc'
UNION ALL
SELECT PM30200.VCHRNMBR,PM30200.VENDORID,PM30200.DOCTYPE,PM30200.DOCDATE,PM30200.POSTEDDT,PM30200.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM30200.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM30200.CURNCYID,TAXSCHID,TEMPSHIPINC.ACTINDX,PRCHAMNT PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID
from PM30200 
inner join (select distinct VNDDOCNM,VCHRNMBR,POP30300.VENDORID,POP30390.ACTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID from POP30300 
inner join POP10600 on POP30300.POPRCTNM = POP10600.POPIVCNO
inner join POP30390 on POP10600.POPRCTNM = POP30390.POPRCTNM and POP30390.VENDORID = POP30300.VENDORID 
and DISTTYPE = 1 inner join nfRET_GL00101 on POP30390.ACTINDX = nfRET_GL00101.ACTINDX) TEMPSHIPINC on PM30200.VCHRNMBR = TEMPSHIPINC.VCHRNMBR and PM30200.VENDORID = TEMPSHIPINC.VENDORID 
where PM30200.DOCTYPE in (1,2,3)  and VOIDED = 0 and BCHSOURC = 'Rcvg Trx Ivc'

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfRET_Invoices]  TO [DYNGRP] 
GO 

/*End_nfRET_Invoices*/
/*Begin_nfRET_Invoices_Opn*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfRET_Invoices_Opn]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfRET_Invoices_Opn]
GO

Create VIEW nfRET_Invoices_Opn as
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM20000.CURNCYID,TAXSCHID, DSTINDX,(CRDTAMNT+DEBITAMT)-isnull(APPAMT,0) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID
from PM20000 inner join PM10100 on PM20000.VCHRNMBR = PM10100.VCHRNMBR and PM20000.VENDORID = PM10100.VENDORID 
inner join nfRET_GL00101 on PM10100.DSTINDX = nfRET_GL00101.ACTINDX
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where DOCTYPE in (1,2,3) and DISTTYPE in (5,6) and VOIDED = 0 and BCHSOURC <> 'Rcvg Trx Ivc'
UNION ALL
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM20000.CURNCYID,TAXSCHID,TEMPSHIPINC.ACTINDX,PRCHAMNT-isnull(APPAMT,0) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID
from PM20000 
inner join (select distinct VNDDOCNM,VCHRNMBR,POP30300.VENDORID,POP30390.ACTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID from POP30300 
inner join POP10600 on POP30300.POPRCTNM = POP10600.POPIVCNO
inner join POP30390 on POP10600.POPRCTNM = POP30390.POPRCTNM and POP30390.VENDORID = POP30300.VENDORID 
and DISTTYPE = 1 inner join nfRET_GL00101 on POP30390.ACTINDX = nfRET_GL00101.ACTINDX) TEMPSHIPINC on PM20000.VCHRNMBR = TEMPSHIPINC.VCHRNMBR and PM20000.VENDORID = TEMPSHIPINC.VENDORID 
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where DOCTYPE in (1,2,3)  and VOIDED = 0 and BCHSOURC = 'Rcvg Trx Ivc'

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfRET_Invoices_Opn]  TO [DYNGRP] 
GO 

/*End_nfRET_Invoices_Opn*/
/*Begin_nfRET_Invoices_Opn_VAT*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfRET_Invoices_Opn_VAT]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfRET_Invoices_Opn_VAT]
GO

Create VIEW nfRET_Invoices_Opn_VAT as
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,PM20000.DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,PM20000.TAXAMNT,PM20000.CURNCYID,TAXSCHID, DSTINDX,(CRDTAMNT+DEBITAMT)-isnull(APPAMT,0) PURCHAMT,
nfRETAsset_Prof,nfRET_Retencion_ID,TAXDTLID
from PM20000 inner join PM10100 on PM20000.VCHRNMBR = PM10100.VCHRNMBR and PM20000.VENDORID = PM10100.VENDORID 
inner join nfRET_GL00101 on PM10100.DSTINDX = nfRET_GL00101.ACTINDX
inner join PM10500 on PM20000.VENDORID = PM10500.VENDORID and PM20000.VCHRNMBR = PM10500.VCHRNMBR and PM20000.DOCTYPE = PM10500.DOCTYPE
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where PM20000.DOCTYPE in (1,2,3) and DISTTYPE in (5,6) and VOIDED = 0 and BCHSOURC <> 'Rcvg Trx Ivc'
UNION ALL
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,PM20000.DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,PM20000.TAXAMNT,PM20000.CURNCYID,TAXSCHID,TEMPSHIPINC.ACTINDX,PRCHAMNT-isnull(APPAMT,0) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID,TAXDTLID
from PM20000 
inner join (select distinct VNDDOCNM,VCHRNMBR,POP30300.VENDORID,POP30390.ACTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID from POP30300 
inner join POP10600 on POP30300.POPRCTNM = POP10600.POPIVCNO
inner join POP30390 on POP10600.POPRCTNM = POP30390.POPRCTNM and POP30390.VENDORID = POP30300.VENDORID 
and DISTTYPE = 1 inner join nfRET_GL00101 on POP30390.ACTINDX = nfRET_GL00101.ACTINDX) TEMPSHIPINC on PM20000.VCHRNMBR = TEMPSHIPINC.VCHRNMBR and PM20000.VENDORID = TEMPSHIPINC.VENDORID 
inner join PM10500 on PM20000.VENDORID = PM10500.VENDORID and PM20000.VCHRNMBR = PM10500.VCHRNMBR and PM20000.DOCTYPE = PM10500.DOCTYPE
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where PM20000.DOCTYPE in (1,2,3)  and VOIDED = 0 and BCHSOURC = 'Rcvg Trx Ivc'
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfRET_Invoices_Opn_VAT]  TO [DYNGRP] 
GO 

/*End_nfRET_Invoices_Opn_VAT*/
/*Begin_nfRET_Invoices_Opn_WTH*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfRET_Invoices_Opn_WTH]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfRET_Invoices_Opn_WTH]
GO

Create VIEW nfRET_Invoices_Opn_WTH as
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM20000.CURNCYID,TAXSCHID, DSTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID
from PM20000 inner join PM10100 on PM20000.VCHRNMBR = PM10100.VCHRNMBR and PM20000.VENDORID = PM10100.VENDORID 
inner join nfRET_GL00101 on PM10100.DSTINDX = nfRET_GL00101.ACTINDX
where DOCTYPE in (1,2,3) and DISTTYPE in (5,6) and VOIDED = 0 and BCHSOURC <> 'Rcvg Trx Ivc'

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfRET_Invoices_Opn_WTH]  TO [DYNGRP] 
GO 

/*End_nfRET_Invoices_Opn_WTH*/
/*Begin_nfRET_Invoices_VAT*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfRET_Invoices_VAT]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfRET_Invoices_VAT]
GO

Create VIEW nfRET_Invoices_VAT as
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,PM20000.DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,PM20000.TAXAMNT,PM20000.CURNCYID,TAXSCHID, DSTINDX,(CRDTAMNT+DEBITAMT)-isnull(APPAMT,0) PURCHAMT,
nfRETAsset_Prof,nfRET_Retencion_ID,TAXDTLID
from PM20000 inner join PM10100 on PM20000.VCHRNMBR = PM10100.VCHRNMBR and PM20000.VENDORID = PM10100.VENDORID 
inner join nfRET_GL00101 on PM10100.DSTINDX = nfRET_GL00101.ACTINDX
inner join PM10500 on PM20000.VENDORID = PM10500.VENDORID and PM20000.VCHRNMBR = PM10500.VCHRNMBR and PM20000.DOCTYPE = PM10500.DOCTYPE
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where PM20000.DOCTYPE in (1,2,3) and DISTTYPE in (5,6)  and VOIDED = 0 and BCHSOURC <> 'Rcvg Trx Ivc'
UNION ALL
SELECT PM30200.VCHRNMBR,PM30200.VENDORID,PM30200.DOCTYPE,PM30200.DOCDATE,PM30200.POSTEDDT,PM30200.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM30200.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,PM30200.TAXAMNT,PM30200.CURNCYID,TAXSCHID, DSTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID,TAXDTLID
from PM30200 inner join PM30600 on PM30200.VCHRNMBR = PM30600.VCHRNMBR and PM30200.VENDORID = PM30600.VENDORID  and PM30200.DOCTYPE = PM30600.DOCTYPE
inner join nfRET_GL00101 on PM30600.DSTINDX = nfRET_GL00101.ACTINDX
inner join PM30700 on PM30200.VENDORID = PM30700.VENDORID and PM30200.VCHRNMBR = PM30700.VCHRNMBR and PM30200.DOCTYPE = PM30700.DOCTYPE
where PM30200.DOCTYPE in (1,2,3) and DISTTYPE in (5,6) and VOIDED = 0 and BCHSOURC <> 'Rcvg Trx Ivc'
UNION ALL
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,PM20000.DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,PM20000.TAXAMNT,PM20000.CURNCYID,TAXSCHID,TEMPSHIPINC.ACTINDX,PRCHAMNT-isnull(APPAMT,0) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID,TAXDTLID
from PM20000 
inner join (select distinct VNDDOCNM,VCHRNMBR,POP30300.VENDORID,POP30390.ACTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID from POP30300 
inner join POP10600 on POP30300.POPRCTNM = POP10600.POPIVCNO
inner join POP30390 on POP10600.POPRCTNM = POP30390.POPRCTNM and POP30390.VENDORID = POP30300.VENDORID 
and DISTTYPE = 1 inner join nfRET_GL00101 on POP30390.ACTINDX = nfRET_GL00101.ACTINDX) TEMPSHIPINC on PM20000.VCHRNMBR = TEMPSHIPINC.VCHRNMBR and PM20000.VENDORID = TEMPSHIPINC.VENDORID 
inner join PM10500 on PM20000.VENDORID = PM10500.VENDORID and PM20000.VCHRNMBR = PM10500.VCHRNMBR and PM20000.DOCTYPE = PM10500.DOCTYPE
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where PM20000.DOCTYPE in (1,2,3)  and VOIDED = 0 and BCHSOURC = 'Rcvg Trx Ivc'
UNION ALL
SELECT PM30200.VCHRNMBR,PM30200.VENDORID,PM30200.DOCTYPE,PM30200.DOCDATE,PM30200.POSTEDDT,PM30200.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM30200.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,PM30200.TAXAMNT,PM30200.CURNCYID,TAXSCHID, TEMPSHIPINC.ACTINDX ,PRCHAMNT PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID,TAXDTLID
from PM30200 inner join (select distinct VNDDOCNM,VCHRNMBR,POP30300.VENDORID,POP30390.ACTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID from POP30300 
inner join POP10600 on POP30300.POPRCTNM = POP10600.POPIVCNO
inner join POP30390 on POP10600.POPRCTNM = POP30390.POPRCTNM and POP30390.VENDORID = POP30300.VENDORID 
and DISTTYPE = 1 inner join nfRET_GL00101 on POP30390.ACTINDX = nfRET_GL00101.ACTINDX) TEMPSHIPINC on PM30200.VCHRNMBR = TEMPSHIPINC.VCHRNMBR and PM30200.VENDORID = TEMPSHIPINC.VENDORID 
inner join PM30700 on PM30200.VENDORID = PM30700.VENDORID and PM30200.VCHRNMBR = PM30700.VCHRNMBR and PM30200.DOCTYPE = PM30700.DOCTYPE
where PM30200.DOCTYPE in (1,2,3)  and VOIDED = 0 and BCHSOURC = 'Rcvg Trx Ivc'

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfRET_Invoices_VAT]  TO [DYNGRP] 
GO 

/*End_nfRET_Invoices_VAT*/
/*Begin_nfRET_Payments*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfRET_Payments]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfRET_Payments]
GO

Create VIEW nfRET_Payments as
SELECT VCHRNMBR,VENDORID,DOCTYPE,DOCDATE,PSTGDATE,DOCNUMBR,DOCAMNT PAYAMT,TRXSORCE,BCHSOURC,PRCHAMNT,CURNCYID,TAXSCHID
from PM20000 where DOCTYPE = 6 and VOIDED = 0
UNION ALL
SELECT VCHRNMBR,VENDORID,DOCTYPE,DOCDATE,PSTGDATE,DOCNUMBR,DOCAMNT PAYAMT,TRXSORCE,BCHSOURC,PRCHAMNT,CURNCYID,TAXSCHID
from PM30200 where DOCTYPE = 6 and VOIDED = 0

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfRET_Payments]  TO [DYNGRP] 
GO 

/*End_nfRET_Payments*/
/*Begin_nfRET_Shipment_Opn_WTH*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfRET_Shipment_Opn_WTH]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfRET_Shipment_Opn_WTH]
GO

CREATE VIEW nfRET_Shipment_Opn_WTH as
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM20000.CURNCYID,TAXSCHID,TEMPSHIPINC.ACTINDX,TEMPSHIPINC.PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID
from PM20000 
inner join (select distinct VNDDOCNM,VCHRNMBR,POP30300.VENDORID,POP30390.ACTINDX,EXTDCOST PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID from POP30300 
inner join POP10600 on POP30300.POPRCTNM = POP10600.POPIVCNO
inner join POP30390 on POP10600.POPRCTNM = POP30390.POPRCTNM and POP30390.VENDORID = POP30300.VENDORID 
and DISTTYPE = 1 
inner join POP30310 on POP10600.POPIVCNO = POP30310.POPRCTNM and POP30390.ACTINDX = POP30310.INVINDX
inner join nfRET_GL00101 on POP30390.ACTINDX = nfRET_GL00101.ACTINDX) TEMPSHIPINC on PM20000.VCHRNMBR = TEMPSHIPINC.VCHRNMBR and PM20000.VENDORID = TEMPSHIPINC.VENDORID 
where DOCTYPE in (1,2,3)  and VOIDED = 0 and BCHSOURC = 'Rcvg Trx Ivc'

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfRET_Shipment_Opn_WTH]  TO [DYNGRP] 
GO 

/*End_nfRET_Shipment_Opn_WTH*/
/*Begin_nfRET_IsValid_Invoices*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nfRET_IsValid_Invoices]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[nfRET_IsValid_Invoices]
GO

CREATE VIEW nfRET_IsValid_Invoices as
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM20000.CURNCYID,TAXSCHID, DSTINDX,(CRDTAMNT+DEBITAMT)-isnull(APPAMT,0) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID
from PM20000 inner join PM10100 on PM20000.VCHRNMBR = PM10100.VCHRNMBR and PM20000.VENDORID = PM10100.VENDORID 
inner join nfRET_GL00101 on PM10100.DSTINDX = nfRET_GL00101.ACTINDX
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where DOCTYPE in (1,2,3) and DISTTYPE in (5,6) and VOIDED = 0 and BCHSOURC <> 'Rcvg Trx Ivc'
UNION ALL
SELECT PM20000.VCHRNMBR,PM20000.VENDORID,DOCTYPE,PM20000.DOCDATE,PM20000.POSTEDDT,PM20000.PSTGDATE,DOCNUMBR,DOCAMNT,CURTRXAM,PM20000.TRXSORCE,
BCHSOURC,PRCHAMNT,TRDISAMT,MSCCHAMT,FRTAMNT,TAXAMNT,PM20000.CURNCYID,TAXSCHID,TEMPSHIPINC.ACTINDX,PRCHAMNT-isnull(APPAMT,0) PURCHAMT,nfRETAsset_Prof,
nfRET_Retencion_ID
from PM20000 
inner join (select distinct VNDDOCNM,VCHRNMBR,POP30300.VENDORID,POP30390.ACTINDX,(CRDTAMNT+DEBITAMT) PURCHAMT,nfRETAsset_Prof,nfRET_Retencion_ID from POP30300 
inner join POP10600 on POP30300.POPRCTNM = POP10600.POPIVCNO
inner join POP30390 on POP10600.POPRCTNM = POP30390.POPRCTNM and POP30390.VENDORID = POP30300.VENDORID and DISTTYPE = 1 
inner join POP30310 on POP10600.POPIVCNO = POP30310.POPRCTNM and POP30390.ACTINDX = POP30310.INVINDX and POP10600.IVCLINNO = POP30310.RCPTLNNM
inner join nfRET_GL00101 on POP30390.ACTINDX = nfRET_GL00101.ACTINDX) TEMPSHIPINC on PM20000.VCHRNMBR = TEMPSHIPINC.VCHRNMBR and PM20000.VENDORID = TEMPSHIPINC.VENDORID 
left outer join(SELECT VENDORID,APTVCHNM,sum(APPLDAMT) APPAMT from PM20100 where DOCTYPE in (4,5) group by VENDORID,APTVCHNM) TEMPPM20100
on PM20000.VCHRNMBR = TEMPPM20100.APTVCHNM and PM20000.VENDORID = TEMPPM20100.VENDORID 
where DOCTYPE in (1,2,3)  and VOIDED = 0 and BCHSOURC = 'Rcvg Trx Ivc'
go
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON [dbo].[nfRET_IsValid_Invoices]  TO [DYNGRP] 
GO 

/*End_nfRET_IsValid_Invoices*/

