/*Count : 6 */
 
set DATEFORMAT ymd 
GO 
 
/*Begin_AWLI_ReporteImpuestos*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[AWLI_ReporteImpuestos]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[AWLI_ReporteImpuestos]
GO

CREATE PROCEDURE AWLI_ReporteImpuestos 
@IDReporte AS CHAR(15),
@USERID AS CHAR(15),
@COL_22 AS VARCHAR(15) = NULL 
AS

EXEC AWLI_ReporteImpuestos_LlenoHeaders @IDReporte,@USERID

DELETE FROM AWLI50003 WHERE RPTID=@IDReporte AND USERID=@USERID  

DECLARE @TipoReporte as SMALLINT, @HISTORY as TINYINT, @UNPSTTRX as TINYINT, @OPENTRX as TINYINT, @SORTBY1 as SMALLINT
DECLARE @AWFiltraXDocumentDate as TINYINT, @STTDOCDT as DATETIME, @ENDDOCDT as DATETIME, @AWFiltraXPostDate as TINYINT
DECLARE @STTPSTDT as DATETIME, @ENDPSTDT as DATETIME, @TipoCorteControl as smallint
DECLARE @RM_SALESINV as tinyint, @RM_DEBITMEM as tinyint, @RM_FINCHRGS as tinyint, @RM_SERVNREP as tinyint, @RM_WARRANTY as tinyint
DECLARE @RM_CREDMEMO as tinyint, @RM_RETURNS as tinyint, @PM_INVOICE as tinyint, @PM_FINCHR as tinyint, @PM_MISCHARG AS tinyint, @PM_RETURN as tinyint
DECLARE @PM_CRDMEM as tinyint, @FiltraSOPDOC as tinyint

SELECT @TipoReporte=TipoReporte, @HISTORY=HISTORY, @UNPSTTRX=UNPSTTRX, @OPENTRX=OpenTRX, @SORTBY1=SORTBY1, 
 @AWFiltraXDocumentDate=AWFiltraXDocumentDate, @STTDOCDT=STTDOCDT, @ENDDOCDT=ENDDOCDT,  @AWFiltraXPostDate=AWFiltraXPostDate, 
 @STTPSTDT=STTPSTDT, @ENDPSTDT=ENDPSTDT, @TipoCorteControl=TipoCorteControl,
 @RM_SALESINV=SALESINV, @RM_DEBITMEM=DEBITMEM, @RM_FINCHRGS=FINCHRGS, @RM_SERVNREP=SERVNREP, @RM_WARRANTY=WARRANTY,
 @RM_CREDMEMO=CREDMEMO, @RM_RETURNS=RETURNS, @PM_INVOICE=PMINVOIC, @PM_FINCHR=PMFINCHR, @PM_MISCHARG=MISCHARG,
 @PM_RETURN=PMRETURN, @PM_CRDMEM=PMCRDMEM, @FiltraSOPDOC=AWLI_Filtra_SOP_Doc
FROM AWLI40001 WHERE @IDReporte=RPTID

DECLARE @D_TYPE AS INT, @D_STATE AS VARCHAR(4), @D_DOCTYPE AS INT, @D_DOCNUMBR AS CHAR(21), @D_VCHRNMBR AS CHAR(21), @D_DOCDATE AS DATETIME
DECLARE @D_GLPOSTDT AS DATETIME, @D_CUSTVENDID AS CHAR(15), @D_CUSTVENDNAME AS CHAR(65), @D_TXRGNNUM AS CHAR(25)
DECLARE @D_SALESPURCHAMNT AS NUMERIC(19,5), @D_TRDISAMT AS NUMERIC(19,5), @D_FRTAMNT AS NUMERIC(19,5), @D_MISCAMNT AS NUMERIC(19,5)
DECLARE @D_TAXAMNT AS NUMERIC(19,5), @D_DOCAMNT AS NUMERIC(19,5), @D_VOIDED AS INT, @D_DOCID AS CHAR(15), @D_DOCTYPEDESC AS VARCHAR(7), @D_VOIDDATE AS DATETIME, @D_CURNCYID AS CHAR(15)

DECLARE @T_TYPE AS INT, @T_DOCTYPE AS INT, @T_VCHRNMBR AS CHAR(21), @T_TAXDTLID AS CHAR(15), @T_TAXAMNT AS NUMERIC(19,5)
DECLARE @T_TAXDTAMT AS NUMERIC(19,5), @T_TDTTXAMT AS NUMERIC(19,5)
DECLARE @NumeroDeOrden as SMALLINT, @IDGRUPOIMP as CHAR(15), @DESCGRUPOIMP AS CHAR(31)

DECLARE @COL01 AS NUMERIC(19,5), @COL02 AS NUMERIC(19,5), @COL03 AS NUMERIC(19,5), @COL04 AS NUMERIC(19,5), @COL05 AS NUMERIC(19,5)
DECLARE @COL06 AS NUMERIC(19,5), @COL07 AS NUMERIC(19,5), @COL08 AS NUMERIC(19,5), @COL09 AS NUMERIC(19,5), @COL10 AS NUMERIC(19,5)
DECLARE @COL11 AS NUMERIC(19,5), @COL12 AS NUMERIC(19,5), @COL13 AS NUMERIC(19,5), @COL14 AS NUMERIC(19,5), @COL15 AS NUMERIC(19,5)
DECLARE @COL16 AS NUMERIC(19,5), @COL17 AS NUMERIC(19,5), @COL18 AS NUMERIC(19,5), @COL19 AS NUMERIC(19,5), @COL20 AS NUMERIC(19,5)
DECLARE @MONTO AS NUMERIC(19,5), @OPERACION AS INTEGER
DECLARE @T_COL01 AS NUMERIC(19,5), @T_COL02 AS NUMERIC(19,5), @T_COL03 AS NUMERIC(19,5), @T_COL04 AS NUMERIC(19,5), @T_COL05 AS NUMERIC(19,5)
DECLARE @T_COL06 AS NUMERIC(19,5), @T_COL07 AS NUMERIC(19,5), @T_COL08 AS NUMERIC(19,5), @T_COL09 AS NUMERIC(19,5), @T_COL10 AS NUMERIC(19,5)
DECLARE @T_COL11 AS NUMERIC(19,5), @T_COL12 AS NUMERIC(19,5), @T_COL13 AS NUMERIC(19,5), @T_COL14 AS NUMERIC(19,5), @T_COL15 AS NUMERIC(19,5)
DECLARE @T_COL16 AS NUMERIC(19,5), @T_COL17 AS NUMERIC(19,5), @T_COL18 AS NUMERIC(19,5), @T_COL19 AS NUMERIC(19,5), @T_COL20 AS NUMERIC(19,5)
DECLARE @NROGRUPO AS SMALLINT, @IDGRUPO as CHAR(15), @DESCGRUPO AS CHAR(31)

DECLARE @COL_NROORDCOL AS INTEGER, @COL_TIPOIMP AS INTEGER, @COL_OPVTAX AS INTEGER, @COL_TAXDTLID AS CHAR(15)


 If @TipoReporte=1 AND @SORTBY1=1 
  DECLARE DOCUMENTOS CURSOR FOR SELECT * FROM AWLI_DOCUMENTOS 
  WHERE  TYPE=1 AND  ((DOCTYPE=1 AND @PM_INVOICE=1) OR  (DOCTYPE=2 AND @PM_FINCHR=1) OR  (DOCTYPE=3 AND @PM_MISCHARG=1) OR 
      (DOCTYPE=4 AND @PM_RETURN=1) OR (DOCTYPE=5 AND @PM_CRDMEM=1))  AND ((STATE='WORK' AND @UNPSTTRX=1) OR 
      (STATE='OPEN' AND @OPENTRX=1) OR (STATE='HIST' AND @HISTORY=1)) AND (NOT @AWFiltraXDocumentDate=1 OR 
     (DOCDATE >=@STTDOCDT AND DOCDATE<=@ENDDOCDT)) AND (NOT @AWFiltraXPostDate=1 OR (GLPOSTDT >=@STTPSTDT AND 
     GLPOSTDT<=@ENDPSTDT))
  ORDER BY DOCDATE,DOCNUMBR 
 else If @TipoReporte=1 AND @SORTBY1=2  
  DECLARE DOCUMENTOS CURSOR FOR SELECT * FROM AWLI_DOCUMENTOS 
  WHERE TYPE=1 AND ((DOCTYPE=1 AND @PM_INVOICE=1) OR (DOCTYPE=2 AND @PM_FINCHR=1) OR (DOCTYPE=3 AND @PM_MISCHARG=1) OR 
     (DOCTYPE=4 AND @PM_RETURN=1) OR (DOCTYPE=5 AND @PM_CRDMEM=1)) AND ((STATE='WORK' AND @UNPSTTRX=1) OR 
      (STATE='OPEN' AND @OPENTRX=1) OR (STATE='HIST' AND @HISTORY=1)) AND (NOT @AWFiltraXDocumentDate=1 OR 
     (DOCDATE >=@STTDOCDT AND DOCDATE<=@ENDDOCDT)) AND (NOT @AWFiltraXPostDate=1 OR (GLPOSTDT >=@STTPSTDT AND 
     GLPOSTDT<=@ENDPSTDT)) 
  ORDER BY DOCDATE,CUSTVENDID, DOCNUMBR 
 else if @TipoReporte=2 AND @SORTBY1=1   
  DECLARE DOCUMENTOS CURSOR FOR SELECT * FROM AWLI_DOCUMENTOS 
  WHERE TYPE=2 AND ((DOCTYPE=1 AND @RM_SALESINV=1) OR (DOCTYPE=3 AND @RM_DEBITMEM=1) OR (DOCTYPE=4 AND @RM_FINCHRGS=1) OR 
     (DOCTYPE=5 AND @RM_SERVNREP=1) OR (DOCTYPE=6 AND @RM_WARRANTY=1) OR  (DOCTYPE=7 AND @RM_CREDMEMO=1) OR 
      (DOCTYPE=8 AND @RM_RETURNS=1) ) AND ((STATE='WORK' AND @UNPSTTRX=1) OR (STATE='OPEN' AND @OPENTRX=1) OR 
      (STATE='HIST' AND @HISTORY=1)) AND (NOT @AWFiltraXDocumentDate=1 OR (DOCDATE >=@STTDOCDT AND DOCDATE<=@ENDDOCDT)) AND 
     (NOT @AWFiltraXPostDate=1 OR (GLPOSTDT >=@STTPSTDT AND GLPOSTDT<=@ENDPSTDT)) AND ((DOCID = '') OR 
      NOT EXISTS  (SELECT  *  FROM AWLI40003  WHERE  AWLI_DOCUMENTOS.DOCID = AWLI40003.DOCID AND RPTID = @IDReporte) OR 
     NOT (@FiltraSOPDOC = 1)) 
  ORDER BY DOCDATE,DOCNUMBR 
 else if @TipoReporte=2 AND @SORTBY1=2   
  DECLARE DOCUMENTOS CURSOR FOR SELECT * FROM AWLI_DOCUMENTOS 
  WHERE TYPE=2 AND ((DOCTYPE=1 AND @RM_SALESINV=1) OR (DOCTYPE=3 AND @RM_DEBITMEM=1) OR (DOCTYPE=4 AND @RM_FINCHRGS=1) OR 
      (DOCTYPE=5 AND @RM_SERVNREP=1) OR (DOCTYPE=6 AND @RM_WARRANTY=1) OR (DOCTYPE=7 AND @RM_CREDMEMO=1) OR 
      (DOCTYPE=8 AND @RM_RETURNS=1) ) AND ((STATE='WORK' AND @UNPSTTRX=1) OR (STATE='OPEN' AND @OPENTRX=1) OR 
      (STATE='HIST' AND @HISTORY=1)) AND (NOT @AWFiltraXDocumentDate=1 OR (DOCDATE >=@STTDOCDT AND DOCDATE<=@ENDDOCDT)) AND 
     (NOT @AWFiltraXPostDate=1 OR (GLPOSTDT >=@STTPSTDT AND GLPOSTDT<=@ENDPSTDT)) AND ((DOCID = '') OR 
     NOT EXISTS  (SELECT  *  FROM AWLI40003  WHERE  AWLI_DOCUMENTOS.DOCID = AWLI40003.DOCID AND RPTID = @IDReporte) OR 
     NOT (@FiltraSOPDOC = 1)) 
  ORDER BY DOCDATE,CUSTVENDID, DOCNUMBR 
 else return 
 

 OPEN  DOCUMENTOS
 FETCH NEXT FROM DOCUMENTOS INTO @D_TYPE, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, @D_DOCDATE,@D_GLPOSTDT, @D_CUSTVENDID,
       @D_CUSTVENDNAME,  @D_TXRGNNUM, @D_SALESPURCHAMNT, @D_TRDISAMT, @D_FRTAMNT, @D_MISCAMNT, @D_TAXAMNT,
      @D_DOCAMNT, @D_VOIDED, @D_DOCID, @D_DOCTYPEDESC, @D_VOIDDATE, @D_CURNCYID


 WHILE (@@FETCH_STATUS=0)    
      BEGIN 
  
   SELECT @COL01=0, @COL02=0, @COL03=0, @COL04=0, @COL05=0, @COL06=0, @COL07=0, @COL08=0, @COL09=0, @COL10=0, @COL11=0, @COL12=0, @COL13=0, @COL14=0, @COL15=0, @COL16=0, @COL17=0, @COL18=0, @COL19=0, @COL20=0
  
   EXEC AWLI_ReporteImpuestos_AcumuloColumnaTotales @IDReporte,@USERID,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT,
          @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08,@COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20,
          @COL01 OUTPUT,@COL02 OUTPUT,@COL03 OUTPUT,@COL04 OUTPUT,@COL05 OUTPUT,@COL06 OUTPUT,@COL07 OUTPUT,@COL08 OUTPUT,
          @COL09 OUTPUT,@COL10 OUTPUT,@COL11 OUTPUT,@COL12 OUTPUT,@COL13 OUTPUT,@COL14 OUTPUT,@COL15 OUTPUT, 
          @COL16 OUTPUT,@COL17 OUTPUT,@COL18 OUTPUT,@COL19 OUTPUT,@COL20 OUTPUT 
  
   
    DECLARE DOC_IMPUESTOS CURSOR FOR 
    SELECT    AWLI_IMPUESTOS.*, ISNULL(GRUPOIMP.NumeroDeOrden, 0) AS NumeroDeOrden, ISNULL(GRUPOIMP.IDGRIMP, '')  AS IDGRUPOIMP, ISNULL(GRUPOIMP.DSCRIPTN, '') AS DSCRIPTN 
    FROM        AWLI_IMPUESTOS LEFT OUTER JOIN 
                              (SELECT     AWLI40202.TAXDTLID, AWLI40002.RPTID, AWLI40002.NumeroDeOrden, AWLI40202.IDGRIMP, AWLI40002.DSCRIPTN 
                                FROM          AWLI40002 INNER JOIN 
                                                       AWLI40202 ON AWLI40002.IDGRIMP = AWLI40202.IDGRIMP 
                                WHERE      (AWLI40002.RPTID = @IDReporte)) GRUPOIMP ON GRUPOIMP.TAXDTLID = dbo.AWLI_IMPUESTOS.TAXDTLID 
    WHERE     (TYPE=@D_TYPE AND DOCTYPE=@D_DOCTYPE AND VCHRNMBR=@D_VCHRNMBR) AND 
       
      (  NOT EXISTS  (SELECT     TipoCorteControl FROM AWLI40001 WHERE      AWLI40001.RPTID = @IDReporte AND TipoCorteControl = 2) OR 
     NOT  (GRUPOIMP.NumeroDeOrden IS NULL)  ) 
    ORDER BY GRUPOIMP.NumeroDeOrden, dbo.AWLI_IMPUESTOS.TAXDTLID 
    OPEN DOC_IMPUESTOS
   
    FETCH NEXT FROM DOC_IMPUESTOS INTO @T_TYPE, @T_DOCTYPE, @T_VCHRNMBR, @T_TAXDTLID, @T_TAXAMNT, @T_TAXDTAMT,
          @T_TDTTXAMT, @NumeroDeOrden, @IDGRUPOIMP,@DESCGRUPOIMP 
   
    IF @TipoCorteControl=1
         BEGIN select @NumeroDeOrden=0, @IDGRUPOIMP='', @DESCGRUPOIMP='' END
   
    IF (@@FETCH_STATUS=0)     
         BEGIN 
     
      SELECT @NROGRUPO=@NumeroDeOrden, @IDGRUPO= @IDGRUPOIMP, @DESCGRUPO=@DESCGRUPOIMP
      SELECT @T_COL01=@COL01, @T_COL02=@COL02, @T_COL03=@COL03, @T_COL04=@COL04, @T_COL05=@COL05, @T_COL06=@COL06, @T_COL07=@COL07, @T_COL08=@COL08,
        @T_COL09=@COL09, @T_COL10=@COL10, @T_COL11=@COL11, @T_COL12=@COL12, @T_COL13=@COL13, @T_COL14=@COL14, @T_COL15=@COL15, 
        @T_COL16=@COL16, @T_COL17=@COL17, @T_COL18=@COL18, @T_COL19=@COL19, @T_COL20=@COL20 
     
      WHILE (@@FETCH_STATUS=0)
           BEGIN  
       
        EXEC AWLI_ReporteImpuestos_AcumuloColumnaImpuestos @IDReporte, @USERID, @T_TAXDTLID, @T_TAXAMNT,@T_TAXDTAMT,@T_TDTTXAMT, @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,
               @T_COL08,@T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,
               @T_COL01 OUTPUT,@T_COL02 OUTPUT,@T_COL03 OUTPUT,@T_COL04 OUTPUT,@T_COL05 OUTPUT,@T_COL06 OUTPUT,@T_COL07 OUTPUT,@T_COL08 OUTPUT,
               @T_COL09 OUTPUT,@T_COL10 OUTPUT,@T_COL11 OUTPUT,@T_COL12 OUTPUT,@T_COL13 OUTPUT,@T_COL14 OUTPUT,@T_COL15 OUTPUT,@T_COL16 OUTPUT,@T_COL17 OUTPUT,@T_COL18 OUTPUT,@T_COL19 OUTPUT,@T_COL20 OUTPUT
       
        FETCH NEXT FROM DOC_IMPUESTOS INTO @T_TYPE, @T_DOCTYPE, @T_VCHRNMBR, @T_TAXDTLID, @T_TAXAMNT, @T_TAXDTAMT, @T_TDTTXAMT, @NumeroDeOrden, @IDGRUPOIMP,@DESCGRUPOIMP
       
        IF @TipoCorteControl=1 
             BEGIN  
         select @NumeroDeOrden=0, @IDGRUPOIMP='', @DESCGRUPOIMP='' 
             END 
       
        IF (@@FETCH_STATUS=0)
             BEGIN 
         IF @NROGRUPO<>@NumeroDeOrden  
              BEGIN 
          IF (@D_TYPE=1 AND (@D_DOCTYPE=4 OR @D_DOCTYPE=5)) OR (@D_TYPE=2 AND (@D_DOCTYPE=7 OR @D_DOCTYPE=8)) 
               BEGIN   EXEC AWLI_ReporteImpuestos_InserAWLI50003 
            @IDReporte, @USERID, @D_TYPE, @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, 
            @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
            @D_VOIDDATE,@D_CURNCYID,-1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
            @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,@T_COL08, @T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,@COL_22   END
          ELSE 
                BEGIN  EXEC AWLI_ReporteImpuestos_InserAWLI50003 
            @IDReporte, @USERID, @D_TYPE, @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, 
            @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
            @D_VOIDDATE,@D_CURNCYID,1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
            @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,@T_COL08, @T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,@COL_22  END 
          
          SELECT @NROGRUPO=@NumeroDeOrden, @IDGRUPO= @IDGRUPOIMP, @DESCGRUPO=@DESCGRUPOIMP 
          SELECT @T_COL01=@COL01, @T_COL02=@COL02, @T_COL03=@COL03, @T_COL04=@COL04, @T_COL05=@COL05, @T_COL06=@COL06, @T_COL07=@COL07, @T_COL08=@COL08, 
            @T_COL09=@COL09, @T_COL10=@COL10, @T_COL11=@COL11, @T_COL12=@COL12, @T_COL13=@COL13, @T_COL14=@COL14, @T_COL15=@COL15, @T_COL16=@COL16, @T_COL17=@COL17, @T_COL18=@COL18, @T_COL19=@COL19, @T_COL20=@COL20 
              END 
             END  
        ELSE   
             BEGIN 
         IF (@D_TYPE=1 AND (@D_DOCTYPE=4 OR @D_DOCTYPE=5)) OR (@D_TYPE=2 AND (@D_DOCTYPE=7 OR @D_DOCTYPE=8)) 
              BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003 
           @IDReporte, @USERID, @D_TYPE, @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, 
           @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
           @D_VOIDDATE,@D_CURNCYID,-1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
           @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,@T_COL08, @T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,@COL_22  END 
         ELSE 
              BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
           @IDReporte, @USERID, @D_TYPE, @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
           @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
           @D_VOIDDATE,@D_CURNCYID,1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
           @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,@T_COL08, @T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,@COL_22  END 
             END 
           END     
         END 
    ELSE         
         BEGIN 
     IF @TipoCorteControl=1   
          BEGIN 
      IF (@D_TYPE=1 AND (@D_DOCTYPE=4 OR @D_DOCTYPE=5)) OR (@D_TYPE=2 AND (@D_DOCTYPE=7 OR @D_DOCTYPE=8)) 
           BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
        @IDReporte, @USERID, @D_TYPE, 0, '', '', @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
        @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
        @D_VOIDDATE,@D_CURNCYID,-1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
        @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08, @COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20,@COL_22  END 
      ELSE 
           BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
        @IDReporte, @USERID, @D_TYPE, 0, '', '', @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
        @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
        @D_VOIDDATE,@D_CURNCYID,1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
        @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08, @COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20,@COL_22  END 
          END 
     ELSE IF @TipoCorteControl=2   
          BEGIN 
      DECLARE CORTE_CONTROL CURSOR FOR 
      SELECT NumeroDeOrden, IDGRIMP,DSCRIPTN FROM AWLI40002  
      WHERE RPTID=@IDReporte AND INCZERO=1 
      ORDER BY NumeroDeOrden, IDGRIMP 
      OPEN CORTE_CONTROL 
      FETCH NEXT FROM CORTE_CONTROL INTO @NumeroDeOrden, @IDGRUPOIMP,@DESCGRUPO 
      IF (@@FETCH_STATUS<>0) 
           BEGIN SELECT @NumeroDeOrden=0, @IDGRUPO= '', @DESCGRUPO='' END 
      CLOSE CORTE_CONTROL 
      DEALLOCATE CORTE_CONTROL 
      IF (@D_TYPE=1 AND (@D_DOCTYPE=4 OR @D_DOCTYPE=5)) OR (@D_TYPE=2 AND (@D_DOCTYPE=7 OR @D_DOCTYPE=8)) 
           BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
        @IDReporte, @USERID, @D_TYPE, 0, '', '', @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
        @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
        @D_VOIDDATE,@D_CURNCYID,-1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
        @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08, @COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20 END 
      ELSE 
           BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
        @IDReporte, @USERID, @D_TYPE, 0, '', '', @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
        @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
        @D_VOIDDATE,@D_CURNCYID,1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
        @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08, @COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20 END 
          END 
         END 
    
    CLOSE  DOC_IMPUESTOS 
    DEALLOCATE DOC_IMPUESTOS 
    
   FETCH NEXT FROM DOCUMENTOS INTO @D_TYPE, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, @D_DOCDATE, @D_GLPOSTDT,@D_CUSTVENDID, @D_CUSTVENDNAME,   
           @D_TXRGNNUM, @D_SALESPURCHAMNT, @D_TRDISAMT, @D_FRTAMNT, @D_MISCAMNT, @D_TAXAMNT, @D_DOCAMNT, @D_VOIDED, @D_DOCID, @D_DOCTYPEDESC, @D_VOIDDATE,@D_CURNCYID 
      END    
  
 
 CLOSE DOCUMENTOS 
 DEALLOCATE DOCUMENTOS 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[AWLI_ReporteImpuestos] TO [DYNGRP] 
GO 

/*End_AWLI_ReporteImpuestos*/
/*Begin_AWLI_ReporteImpuestos_AcumuloColumnaImpuestos*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[AWLI_ReporteImpuestos_AcumuloColumnaImpuestos]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[AWLI_ReporteImpuestos_AcumuloColumnaImpuestos]
GO

CREATE PROCEDURE AWLI_ReporteImpuestos_AcumuloColumnaImpuestos  
@IDReporte AS CHAR(15),
@USERID AS CHAR(15), 
@T_TAXDTLID AS CHAR(15), 
@T_TAXAMNT AS NUMERIC(19,5), 
@T_TAXDTAMT AS NUMERIC(19,5), 
@T_TDTTXAMT AS NUMERIC(19,5), 
@COL01_IN AS NUMERIC(19,5), 
@COL02_IN AS NUMERIC(19,5), 
@COL03_IN AS NUMERIC(19,5),  
@COL04_IN AS NUMERIC(19,5),  
@COL05_IN AS NUMERIC(19,5),  
@COL06_IN AS NUMERIC(19,5),  
@COL07_IN AS NUMERIC(19,5), 
@COL08_IN AS NUMERIC(19,5), 
@COL09_IN AS NUMERIC(19,5), 
@COL10_IN AS NUMERIC(19,5), 
@COL11_IN AS NUMERIC(19,5), 
@COL12_IN AS NUMERIC(19,5), 
@COL13_IN AS NUMERIC(19,5), 
@COL14_IN AS NUMERIC(19,5), 
@COL15_IN AS NUMERIC(19,5), 
@COL16_IN AS NUMERIC(19,5), 
@COL17_IN AS NUMERIC(19,5), 
@COL18_IN AS NUMERIC(19,5), 
@COL19_IN AS NUMERIC(19,5), 
@COL20_IN AS NUMERIC(19,5), 
@COL01 AS NUMERIC(19,5) OUTPUT, 
@COL02 AS NUMERIC(19,5) OUTPUT, 
@COL03 AS NUMERIC(19,5) OUTPUT,  
@COL04 AS NUMERIC(19,5) OUTPUT,  
@COL05 AS NUMERIC(19,5) OUTPUT,  
@COL06 AS NUMERIC(19,5) OUTPUT,  
@COL07 AS NUMERIC(19,5) OUTPUT, 
@COL08 AS NUMERIC(19,5) OUTPUT, 
@COL09 AS NUMERIC(19,5) OUTPUT, 
@COL10 AS NUMERIC(19,5) OUTPUT, 
@COL11 AS NUMERIC(19,5) OUTPUT, 
@COL12 AS NUMERIC(19,5) OUTPUT, 
@COL13 AS NUMERIC(19,5) OUTPUT, 
@COL14 AS NUMERIC(19,5) OUTPUT, 
@COL15 AS NUMERIC(19,5) OUTPUT, 
@COL16 AS NUMERIC(19,5) OUTPUT, 
@COL17 AS NUMERIC(19,5) OUTPUT, 
@COL18 AS NUMERIC(19,5) OUTPUT, 
@COL19 AS NUMERIC(19,5) OUTPUT, 
@COL20 AS NUMERIC(19,5) OUTPUT 
 
AS 
 
SELECT @COL01=@COL01_IN, @COL02=@COL02_IN, @COL03=@COL03_IN, @COL04=@COL04_IN, @COL05=@COL05_IN, @COL06=@COL06_IN, @COL07=@COL07_IN, @COL08=@COL08_IN, 
 @COL09=@COL09_IN, @COL10=@COL10_IN, @COL11=@COL11_IN, @COL12=@COL12_IN, @COL13=@COL13_IN, @COL14=@COL14_IN, @COL15=@COL15_IN, 
 @COL16=@COL16_IN, @COL17=@COL17_IN, @COL18=@COL18_IN, @COL19=@COL19_IN, @COL20=@COL20_IN 
 
DECLARE @MONTO AS NUMERIC(19,5) 
DECLARE @OPERACION AS INTEGER 
 
 
DECLARE @COL_NROORDCOL AS INTEGER, @COL_TIPOIMP AS INTEGER, @COL_OPVTAX AS INTEGER, @COL_TAXDTLID AS CHAR(15) 
 
 
 DECLARE COL_IMPUESTOS CURSOR FOR 
 SELECT    AWLI40004.NRORDCOL, AWLI40102.TIPOIMP, AWLI40102.OPOVTAX, AWLI40102.TAXDTLID 
 FROM         AWLI40102 INNER JOIN 
                       AWLI40004 ON AWLI40102.IDTAXOP = AWLI40004.IDTAXOP 
 WHERE     (AWLI40004.RPTID = @IDReporte AND AWLI40102.TIPOIMP <4 AND AWLI40102.TIPOIMP >=1 AND AWLI40102.TAXDTLID=@T_TAXDTLID )       
 ORDER BY AWLI40004.RPTID, AWLI40004.NRORDCOL, AWLI40102.TIPOIMP, AWLI40102.TAXDTLID 
 OPEN COL_IMPUESTOS 
 
 
 
 FETCH NEXT FROM COL_IMPUESTOS INTO @COL_NROORDCOL, @COL_TIPOIMP, @COL_OPVTAX, @COL_TAXDTLID 
 WHILE (@@FETCH_STATUS=0) 
      BEGIN 
  SELECT @MONTO=0 
 
   
  IF  @COL_OPVTAX=1  
   SELECT @OPERACION=1   
  ELSE IF @COL_OPVTAX=2  
   SELECT @OPERACION=-1  
  ELSE   
   SELECT @OPERACION=0   
 
   
  IF @COL_TIPOIMP=1 SELECT @MONTO=@OPERACION * @T_TAXAMNT 
  IF @COL_TIPOIMP=2 SELECT @MONTO=@OPERACION * @T_TDTTXAMT 
  IF @COL_TIPOIMP=3 SELECT @MONTO=@OPERACION * @T_TAXDTAMT 
 
     
  IF @COL_NROORDCOL = 1 SELECT @COL01=@COL01+@MONTO 
  ELSE IF @COL_NROORDCOL = 2    SELECT @COL02=@COL02+@MONTO 
  ELSE IF @COL_NROORDCOL = 3    SELECT @COL03=@COL03+@MONTO 
  ELSE IF @COL_NROORDCOL = 4    SELECT @COL04=@COL04+@MONTO 
  ELSE IF @COL_NROORDCOL = 5    SELECT @COL05=@COL05+@MONTO 
  ELSE IF @COL_NROORDCOL = 6    SELECT @COL06=@COL06+@MONTO 
  ELSE IF @COL_NROORDCOL = 7    SELECT @COL07=@COL07+@MONTO 
  ELSE IF @COL_NROORDCOL = 8    SELECT @COL08=@COL08+@MONTO 
  ELSE IF @COL_NROORDCOL = 9    SELECT @COL09=@COL09+@MONTO 
  ELSE IF @COL_NROORDCOL = 10  SELECT @COL10=@COL10+@MONTO 
  ELSE IF @COL_NROORDCOL = 11  SELECT @COL11=@COL11+@MONTO 
  ELSE IF @COL_NROORDCOL = 12  SELECT @COL12=@COL12+@MONTO 
  ELSE IF @COL_NROORDCOL = 13  SELECT @COL13=@COL13+@MONTO 
  ELSE IF @COL_NROORDCOL = 14  SELECT @COL14=@COL14+@MONTO 
  ELSE IF @COL_NROORDCOL = 15  SELECT @COL15=@COL15+@MONTO 
  ELSE IF @COL_NROORDCOL = 16  SELECT @COL16=@COL16+@MONTO 
  ELSE IF @COL_NROORDCOL = 17  SELECT @COL17=@COL17+@MONTO 
  ELSE IF @COL_NROORDCOL = 18  SELECT @COL18=@COL18+@MONTO 
  ELSE IF @COL_NROORDCOL = 19  SELECT @COL19=@COL19+@MONTO 
  ELSE IF @COL_NROORDCOL = 20  SELECT @COL20=@COL20+@MONTO 
 
   
  FETCH NEXT FROM COL_IMPUESTOS INTO @COL_NROORDCOL, @COL_TIPOIMP, @COL_OPVTAX, @COL_TAXDTLID  
      END 
 
     
 CLOSE COL_IMPUESTOS 
 DEALLOCATE COL_IMPUESTOS 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[AWLI_ReporteImpuestos_AcumuloColumnaImpuestos] TO [DYNGRP] 
GO 

/*End_AWLI_ReporteImpuestos_AcumuloColumnaImpuestos*/
/*Begin_AWLI_ReporteImpuestos_AcumuloColumnaTotales*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[AWLI_ReporteImpuestos_AcumuloColumnaTotales]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[AWLI_ReporteImpuestos_AcumuloColumnaTotales]
GO

CREATE PROCEDURE AWLI_ReporteImpuestos_AcumuloColumnaTotales  
@IDReporte AS CHAR(15),
@USERID AS CHAR(15), 
@D_SALESPURCHAMNT AS NUMERIC(19,5), 
@D_TRDISAMT AS NUMERIC(19,5), 
@D_FRTAMNT AS NUMERIC(19,5), 
@D_MISCAMNT AS NUMERIC(19,5), 
@D_TAXAMNT AS NUMERIC(19,5), 
@D_DOCAMNT AS NUMERIC(19,5), 
@COL01_IN AS NUMERIC(19,5), 
@COL02_IN AS NUMERIC(19,5), 
@COL03_IN AS NUMERIC(19,5),  
@COL04_IN AS NUMERIC(19,5),  
@COL05_IN AS NUMERIC(19,5),  
@COL06_IN AS NUMERIC(19,5),  
@COL07_IN AS NUMERIC(19,5), 
@COL08_IN AS NUMERIC(19,5), 
@COL09_IN AS NUMERIC(19,5), 
@COL10_IN AS NUMERIC(19,5), 
@COL11_IN AS NUMERIC(19,5), 
@COL12_IN AS NUMERIC(19,5), 
@COL13_IN AS NUMERIC(19,5), 
@COL14_IN AS NUMERIC(19,5), 
@COL15_IN AS NUMERIC(19,5), 
@COL16_IN AS NUMERIC(19,5), 
@COL17_IN AS NUMERIC(19,5), 
@COL18_IN AS NUMERIC(19,5), 
@COL19_IN AS NUMERIC(19,5), 
@COL20_IN AS NUMERIC(19,5), 
@COL01 AS NUMERIC(19,5) OUTPUT, 
@COL02 AS NUMERIC(19,5) OUTPUT, 
@COL03 AS NUMERIC(19,5) OUTPUT,  
@COL04 AS NUMERIC(19,5) OUTPUT,  
@COL05 AS NUMERIC(19,5) OUTPUT,  
@COL06 AS NUMERIC(19,5) OUTPUT,  
@COL07 AS NUMERIC(19,5) OUTPUT, 
@COL08 AS NUMERIC(19,5) OUTPUT, 
@COL09 AS NUMERIC(19,5) OUTPUT, 
@COL10 AS NUMERIC(19,5) OUTPUT, 
@COL11 AS NUMERIC(19,5) OUTPUT, 
@COL12 AS NUMERIC(19,5) OUTPUT, 
@COL13 AS NUMERIC(19,5) OUTPUT, 
@COL14 AS NUMERIC(19,5) OUTPUT, 
@COL15 AS NUMERIC(19,5) OUTPUT, 
@COL16 AS NUMERIC(19,5) OUTPUT, 
@COL17 AS NUMERIC(19,5) OUTPUT, 
@COL18 AS NUMERIC(19,5) OUTPUT, 
@COL19 AS NUMERIC(19,5) OUTPUT, 
@COL20 AS NUMERIC(19,5) OUTPUT 
 
AS 
 
DECLARE @MONTO AS NUMERIC(19,5) 
DECLARE @OPERACION AS INTEGER 
 
SELECT @COL01=@COL01_IN, @COL02=@COL02_IN, @COL03=@COL03_IN, @COL04=@COL04_IN, @COL05=@COL05_IN, @COL06=@COL06_IN, @COL07=@COL07_IN, @COL08=@COL08_IN, 
 @COL09=@COL09_IN, @COL10=@COL10_IN, @COL11=@COL11_IN, @COL12=@COL12_IN, @COL13=@COL13_IN, @COL14=@COL14_IN, @COL15=@COL15_IN, 
 @COL16=@COL16_IN, @COL17=@COL17_IN, @COL18=@COL18_IN, @COL19=@COL19_IN, @COL20=@COL20_IN 
 
 
 
DECLARE @COL_NROORDCOL AS INTEGER, @COL_TIPOIMP AS INTEGER, @COL_OPVTAX AS INTEGER, @COL_TAXDTLID AS CHAR(15) 
 
 
 DECLARE COL_IMPUESTOS CURSOR FOR 
 SELECT    AWLI40004.NRORDCOL, AWLI40102.TIPOIMP, AWLI40102.OPOVTAX, AWLI40102.TAXDTLID 
 FROM         AWLI40102 INNER JOIN 
                       AWLI40004 ON AWLI40102.IDTAXOP = AWLI40004.IDTAXOP 
 WHERE     (AWLI40004.RPTID = @IDReporte AND AWLI40102.TIPOIMP >=4) 
 ORDER BY AWLI40004.RPTID, AWLI40004.NRORDCOL, AWLI40102.TIPOIMP, AWLI40102.TAXDTLID 
 
 OPEN COL_IMPUESTOS 
 
 
 FETCH NEXT FROM COL_IMPUESTOS INTO @COL_NROORDCOL, @COL_TIPOIMP, @COL_OPVTAX, @COL_TAXDTLID 
 WHILE (@@FETCH_STATUS=0) 
      BEGIN 
   
  SELECT @MONTO=0 
 
   
  IF  @COL_OPVTAX=1  
   SELECT @OPERACION=1   
  ELSE IF @COL_OPVTAX=2  
   SELECT @OPERACION=-1  
  ELSE   
   SELECT @OPERACION=0   
 
   
  IF @COL_TIPOIMP=4 SELECT @MONTO=@OPERACION * @D_SALESPURCHAMNT 
  IF @COL_TIPOIMP=5 SELECT @MONTO=@OPERACION *@D_TRDISAMT 
  IF @COL_TIPOIMP=6 SELECT @MONTO=@OPERACION *@D_FRTAMNT 
  IF @COL_TIPOIMP=7 SELECT @MONTO=@OPERACION *@D_MISCAMNT 
  IF @COL_TIPOIMP=8 SELECT @MONTO=@OPERACION *@D_TAXAMNT 
  IF @COL_TIPOIMP=9 SELECT @MONTO=@OPERACION *@D_DOCAMNT 
 
     
  IF @COL_NROORDCOL = 1 SELECT @COL01=@COL01+@MONTO 
  ELSE IF @COL_NROORDCOL = 2    SELECT @COL02=@COL02+@MONTO 
  ELSE IF @COL_NROORDCOL = 3    SELECT @COL03=@COL03+@MONTO 
  ELSE IF @COL_NROORDCOL = 4    SELECT @COL04=@COL04+@MONTO 
  ELSE IF @COL_NROORDCOL = 5    SELECT @COL05=@COL05+@MONTO 
  ELSE IF @COL_NROORDCOL = 6    SELECT @COL06=@COL06+@MONTO 
  ELSE IF @COL_NROORDCOL = 7    SELECT @COL07=@COL07+@MONTO 
  ELSE IF @COL_NROORDCOL = 8    SELECT @COL08=@COL08+@MONTO 
  ELSE IF @COL_NROORDCOL = 9    SELECT @COL09=@COL09+@MONTO 
  ELSE IF @COL_NROORDCOL = 10  SELECT @COL10=@COL10+@MONTO 
  ELSE IF @COL_NROORDCOL = 11  SELECT @COL11=@COL11+@MONTO 
  ELSE IF @COL_NROORDCOL = 12  SELECT @COL12=@COL12+@MONTO 
  ELSE IF @COL_NROORDCOL = 13  SELECT @COL13=@COL13+@MONTO 
  ELSE IF @COL_NROORDCOL = 14  SELECT @COL14=@COL14+@MONTO 
  ELSE IF @COL_NROORDCOL = 15  SELECT @COL15=@COL15+@MONTO 
  ELSE IF @COL_NROORDCOL = 16  SELECT @COL16=@COL16+@MONTO 
  ELSE IF @COL_NROORDCOL = 17  SELECT @COL17=@COL17+@MONTO 
  ELSE IF @COL_NROORDCOL = 18  SELECT @COL18=@COL18+@MONTO 
  ELSE IF @COL_NROORDCOL = 19  SELECT @COL19=@COL19+@MONTO 
  ELSE IF @COL_NROORDCOL = 20  SELECT @COL20=@COL20+@MONTO 
 
   
  FETCH NEXT FROM COL_IMPUESTOS INTO @COL_NROORDCOL, @COL_TIPOIMP, @COL_OPVTAX, @COL_TAXDTLID 
      END 
 
     
 CLOSE COL_IMPUESTOS 
 DEALLOCATE COL_IMPUESTOS 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[AWLI_ReporteImpuestos_AcumuloColumnaTotales] TO [DYNGRP] 
GO 

/*End_AWLI_ReporteImpuestos_AcumuloColumnaTotales*/
/*Begin_AWLI_ReporteImpuestos_InserAWLI50003*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[AWLI_ReporteImpuestos_InserAWLI50003]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[AWLI_ReporteImpuestos_InserAWLI50003]
GO

CREATE PROCEDURE AWLI_ReporteImpuestos_InserAWLI50003  
@IDReporte AS CHAR(15),
@USERID AS CHAR(15), 
@D_TYPE AS INT, 
@NROGRUPO AS SMALLINT, 
@IDGRUPO as CHAR(15), 
@DESCGRUPO AS CHAR(31), 
@D_STATE AS VARCHAR(4),  
@D_DOCTYPE AS INT,  
@D_DOCNUMBR AS CHAR(21), 
@D_VCHRNMBR AS CHAR(21), 
@D_DOCDATE AS DATETIME,  
@D_GLPOSTDT AS DATETIME,  
@D_CUSTVENDID AS CHAR(15),  
@D_CUSTVENDNAME AS CHAR(65),  
@D_TXRGNNUM AS CHAR(25), 
@D_VOIDED AS INT, 
@D_DOCID AS CHAR(15), 
@D_DOCTYPEDESC AS VARCHAR(7), 
@D_VOIDDATE AS DATETIME,  
@D_CURNCYID AS CHAR(15),  
@OPERACION AS INTEGER, 
@D_SALESPURCHAMNT AS NUMERIC(19,5), 
@D_TRDISAMT AS NUMERIC(19,5), 
@D_FRTAMNT AS NUMERIC(19,5), 
@D_MISCAMNT AS NUMERIC(19,5), 
@D_TAXAMNT AS NUMERIC(19,5), 
@D_DOCAMNT AS NUMERIC(19,5), 
@COL01 AS NUMERIC(19,5), 
@COL02 AS NUMERIC(19,5), 
@COL03 AS NUMERIC(19,5),  
@COL04 AS NUMERIC(19,5),  
@COL05 AS NUMERIC(19,5),  
@COL06 AS NUMERIC(19,5),  
@COL07 AS NUMERIC(19,5), 
@COL08 AS NUMERIC(19,5), 
@COL09 AS NUMERIC(19,5), 
@COL10 AS NUMERIC(19,5), 
@COL11 AS NUMERIC(19,5), 
@COL12 AS NUMERIC(19,5), 
@COL13 AS NUMERIC(19,5), 
@COL14 AS NUMERIC(19,5), 
@COL15 AS NUMERIC(19,5), 
@COL16 AS NUMERIC(19,5), 
@COL17 AS NUMERIC(19,5), 
@COL18 AS NUMERIC(19,5), 
@COL19 AS NUMERIC(19,5), 
@COL20 AS NUMERIC(19,5), 
@COL_20 AS VARCHAR(15) = NULL

AS 
 
DECLARE @TX_COUNT1 as int, @TX_COUNT2 as int , @TX_PCT as NUMERIC(19,5), @COL02_1 AS NUMERIC(19,5) ,@INCTax as INT
	SELECT   @TX_COUNT1 = 0 
	SELECT @COL02_1 = @COL02 
	IF @COL_20 = 'SIRFT' 
		BEGIN 
			SELECT @TX_PCT = TXDTLPCT FROM TX00201 WHERE TAXDTLID IN ( select TAXDTLID from AWLI40102 
			INNER JOIN AWLI40004 ON AWLI40102.IDTAXOP = AWLI40004.IDTAXOP 
			WHERE AWLI40004.RPTID = @IDReporte ) 
		END 
	ELSE 
		BEGIN 
			if len(@COL_20) > 0
			BEGIN 
				SELECT   @TX_COUNT1 = count(1) 
				FROM AWLI40102 INNER JOIN AWLI40004 ON AWLI40102.IDTAXOP = AWLI40004.IDTAXOP
				WHERE AWLI40004.RPTID = @IDReporte AND len(AWLI40102.TAXDTLID) > 0 
			END 
		END 
 
if @TX_COUNT1 > 0 
BEGIN 
		SELECT   @TX_COUNT2 = 0
		SELECT   @TX_COUNT2 = count(1) 
		FROM AWLI_IMPUESTOS_SM WHERE VCHRNMBR = @D_VCHRNMBR AND TAXDTLID IN(SELECT AWLI40102.TAXDTLID
		FROM AWLI40102 INNER JOIN AWLI40004 ON AWLI40102.IDTAXOP = AWLI40004.IDTAXOP WHERE AWLI40004.RPTID = @IDReporte)
END 
 
if @TX_COUNT1 > 0 
BEGIN 
 if @TX_COUNT2 > 0 
	BEGIN 
		INSERT INTO AWLI50003  	 
		(USERID, RPTID, TipoReporte, NumeroDeOrden, IDGRIMP, DSCRIPTN, AWLI_DOCUMENT_STATE,   
	 	DOCTYPE, DOCNUMBR, VCHRNMBR, DOCDATE, GLPOSTDT,  CUSTVNDR, CUSTNAME, TXRGNNUM,          
 		SLSAMNT, TRDISAMT, FRTAMNT, MISCAMNT, TAXAMNT, DOCAMNT, Void, DOCID, AWLI_DOCTYPEDESC, VOIDDATE, CURNCYID, 
 		COLIMP01, COLIMP02, COLIMP03, COLIMP04, COLIMP05, COLIMP06, COLIMP07, COLIMP08, COLIMP09,  
 		COLIMP10, COLIMP11, COLIMP12, COLIMP13, COLIMP14, COLIMP15, COLIMP16, COLIMP17, COLIMP18, COLIMP19, COLIMP20) 
		VALUES 
		(@USERID, @IDReporte, @D_TYPE,   @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, 
		 @D_DOCTYPE, @D_DOCNUMBR,  @D_VCHRNMBR, @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME,  @D_TXRGNNUM,  
 		@D_SALESPURCHAMNT*@OPERACION, @D_TRDISAMT*@OPERACION, @D_FRTAMNT*@OPERACION, @D_MISCAMNT*@OPERACION, @D_TAXAMNT*@OPERACION, @D_DOCAMNT*@OPERACION, 
 		@D_VOIDED, @D_DOCID, @D_DOCTYPEDESC, @D_VOIDDATE, @D_CURNCYID, 
		 @COL01*@OPERACION, @COL02*@OPERACION, @COL03*@OPERACION, @COL04*@OPERACION, @COL05*@OPERACION, @COL06*@OPERACION, @COL07*@OPERACION, @COL08*@OPERACION, @COL09*@OPERACION,  
 		@COL10*@OPERACION, @COL11*@OPERACION, @COL12*@OPERACION, @COL13*@OPERACION, @COL14*@OPERACION, @COL15*@OPERACION, @COL16*@OPERACION, @COL17*@OPERACION, @COL18*@OPERACION, @COL19*@OPERACION, @COL20*@OPERACION) 
 	END 
ELSE
	SELECT @INCTax = TL_WITHOUT_TAX FROM AWLI40001 WHERE RPTID = @IDReporte
	IF @INCTax = 1 
	BEGIN 
		INSERT INTO AWLI50003  	 
		(USERID, RPTID, TipoReporte, NumeroDeOrden, IDGRIMP, DSCRIPTN, AWLI_DOCUMENT_STATE,   
	 	DOCTYPE, DOCNUMBR, VCHRNMBR, DOCDATE, GLPOSTDT,  CUSTVNDR, CUSTNAME, TXRGNNUM,          
 		SLSAMNT, TRDISAMT, FRTAMNT, MISCAMNT, TAXAMNT, DOCAMNT, Void, DOCID, AWLI_DOCTYPEDESC, VOIDDATE, CURNCYID, 
 		COLIMP01, COLIMP02, COLIMP03, COLIMP04, COLIMP05, COLIMP06, COLIMP07, COLIMP08, COLIMP09,  
 		COLIMP10, COLIMP11, COLIMP12, COLIMP13, COLIMP14, COLIMP15, COLIMP16, COLIMP17, COLIMP18, COLIMP19, COLIMP20) 
		VALUES 
		(@USERID, @IDReporte, @D_TYPE,   @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, 
		 @D_DOCTYPE, @D_DOCNUMBR,  @D_VCHRNMBR, @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME,  @D_TXRGNNUM,  
 		@D_SALESPURCHAMNT*@OPERACION, @D_TRDISAMT*@OPERACION, @D_FRTAMNT*@OPERACION, @D_MISCAMNT*@OPERACION, @D_TAXAMNT*@OPERACION, @D_DOCAMNT*@OPERACION, 
 		@D_VOIDED, @D_DOCID, @D_DOCTYPEDESC, @D_VOIDDATE, @D_CURNCYID, 
		 @COL01*@OPERACION, @COL02*@OPERACION, @COL03*@OPERACION, @COL04*@OPERACION, @COL05*@OPERACION, @COL06*@OPERACION, @COL07*@OPERACION, @COL08*@OPERACION, @COL09*@OPERACION,  
 		@COL10*@OPERACION, @COL11*@OPERACION, @COL12*@OPERACION, @COL13*@OPERACION, @COL14*@OPERACION, @COL15*@OPERACION, @COL16*@OPERACION, @COL17*@OPERACION, @COL18*@OPERACION, @COL19*@OPERACION, @COL20*@OPERACION) 
 	END 
 END 
 ELSE 
 	BEGIN 
		INSERT INTO AWLI50003  	 
		(USERID, RPTID, TipoReporte, NumeroDeOrden, IDGRIMP, DSCRIPTN, AWLI_DOCUMENT_STATE,   
	 	DOCTYPE, DOCNUMBR, VCHRNMBR, DOCDATE, GLPOSTDT,  CUSTVNDR, CUSTNAME, TXRGNNUM,          
 		SLSAMNT, TRDISAMT, FRTAMNT, MISCAMNT, TAXAMNT, DOCAMNT, Void, DOCID, AWLI_DOCTYPEDESC, VOIDDATE, CURNCYID, 
 		COLIMP01, COLIMP02, COLIMP03, COLIMP04, COLIMP05, COLIMP06, COLIMP07, COLIMP08, COLIMP09,  
 		COLIMP10, COLIMP11, COLIMP12, COLIMP13, COLIMP14, COLIMP15, COLIMP16, COLIMP17, COLIMP18, COLIMP19, COLIMP20) 
		VALUES 
		(@USERID, @IDReporte, @D_TYPE,   @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, 
 		@D_DOCTYPE, @D_DOCNUMBR,  @D_VCHRNMBR, @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME,  @D_TXRGNNUM,  
 		@D_SALESPURCHAMNT*@OPERACION, @D_TRDISAMT*@OPERACION, @D_FRTAMNT*@OPERACION, @D_MISCAMNT*@OPERACION, @D_TAXAMNT*@OPERACION, @D_DOCAMNT*@OPERACION, 
 		@D_VOIDED, @D_DOCID, @D_DOCTYPEDESC, @D_VOIDDATE, @D_CURNCYID, 
 		@COL01*@OPERACION, @COL02_1*@OPERACION, @COL03*@OPERACION, @COL04*@OPERACION, @COL05*@OPERACION, @COL06*@OPERACION, @COL07*@OPERACION, @COL08*@OPERACION, @COL09*@OPERACION,  
 		@COL10*@OPERACION, @COL11*@OPERACION, @COL12*@OPERACION, @COL13*@OPERACION, @COL14*@OPERACION, @COL15*@OPERACION, @COL16*@OPERACION, @COL17*@OPERACION, @COL18*@OPERACION, @COL19*@OPERACION, @COL20*@OPERACION) 
 	END 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[AWLI_ReporteImpuestos_InserAWLI50003] TO [DYNGRP] 
GO 

/*End_AWLI_ReporteImpuestos_InserAWLI50003*/
/*Begin_AWLI_ReporteImpuestos_LlenoHeaders*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[AWLI_ReporteImpuestos_LlenoHeaders]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[AWLI_ReporteImpuestos_LlenoHeaders]
GO

CREATE PROCEDURE AWLI_ReporteImpuestos_LlenoHeaders  
@IDReporte AS CHAR(15),
@USERID AS CHAR(15)
AS 
 
DELETE FROM AWLI50001 WHERE RPTID=@IDReporte AND USERID=@USERID   
 
 
DECLARE @NROORDCOL AS INT 
DECLARE @DSCRIPTN AS CHAR(31) 
DECLARE @NOMCOL01 AS CHAR(31) 
DECLARE @NOMCOL02 AS CHAR(31) 
DECLARE @NOMCOL03 AS CHAR(31) 
DECLARE @NOMCOL04 AS CHAR(31) 
DECLARE @NOMCOL05 AS CHAR(31) 
DECLARE @NOMCOL06 AS CHAR(31) 
DECLARE @NOMCOL07 AS CHAR(31) 
DECLARE @NOMCOL08 AS CHAR(31) 
DECLARE @NOMCOL09 AS CHAR(31) 
DECLARE @NOMCOL10 AS CHAR(31) 
DECLARE @NOMCOL11 AS CHAR(31) 
DECLARE @NOMCOL12 AS CHAR(31) 
DECLARE @NOMCOL13 AS CHAR(31) 
DECLARE @NOMCOL14 AS CHAR(31) 
DECLARE @NOMCOL15 AS CHAR(31) 
DECLARE @NOMCOL16 AS CHAR(31) 
DECLARE @NOMCOL17 AS CHAR(31) 
DECLARE @NOMCOL18 AS CHAR(31) 
DECLARE @NOMCOL19 AS CHAR(31) 
DECLARE @NOMCOL20 AS CHAR(31) 
 
 
 
DECLARE HEADERS CURSOR FOR 
SELECT NRORDCOL,DSCRIPTN FROM AWLI40004 WHERE RPTID=@IDReporte ORDER BY NRORDCOL 
 
OPEN HEADERS 
 
SELECT @NOMCOL01='',@NOMCOL02='',@NOMCOL03='',@NOMCOL04='',@NOMCOL05='',@NOMCOL06='',@NOMCOL07='',@NOMCOL08='',@NOMCOL09='',@NOMCOL10='',@NOMCOL11='',@NOMCOL12='',@NOMCOL13='',@NOMCOL14='',@NOMCOL15='' 
SELECT @NOMCOL16='',@NOMCOL17='',@NOMCOL18='',@NOMCOL19='',@NOMCOL20='' 
 
FETCH NEXT FROM HEADERS INTO @NROORDCOL,@DSCRIPTN 
WHILE (@@FETCH_STATUS=0)  
     BEGIN  
 IF @NROORDCOL=1 SELECT @NOMCOL01=@DSCRIPTN 
 IF @NROORDCOL=2 SELECT @NOMCOL02=@DSCRIPTN 
 IF @NROORDCOL=3 SELECT @NOMCOL03=@DSCRIPTN 
 IF @NROORDCOL=4 SELECT @NOMCOL04=@DSCRIPTN 
 IF @NROORDCOL=5 SELECT @NOMCOL05=@DSCRIPTN 
 IF @NROORDCOL=6 SELECT @NOMCOL06=@DSCRIPTN 
 IF @NROORDCOL=7 SELECT @NOMCOL07=@DSCRIPTN 
 IF @NROORDCOL=8 SELECT @NOMCOL08=@DSCRIPTN 
 IF @NROORDCOL=9 SELECT @NOMCOL09=@DSCRIPTN 
 IF @NROORDCOL=10 SELECT @NOMCOL10=@DSCRIPTN 
 IF @NROORDCOL=11 SELECT @NOMCOL11=@DSCRIPTN 
 IF @NROORDCOL=12 SELECT @NOMCOL12=@DSCRIPTN 
 IF @NROORDCOL=13 SELECT @NOMCOL13=@DSCRIPTN 
 IF @NROORDCOL=14 SELECT @NOMCOL14=@DSCRIPTN 
 IF @NROORDCOL=15 SELECT @NOMCOL15=@DSCRIPTN 
 IF @NROORDCOL=16 SELECT @NOMCOL16=@DSCRIPTN 
 IF @NROORDCOL=17 SELECT @NOMCOL17=@DSCRIPTN 
 IF @NROORDCOL=18 SELECT @NOMCOL18=@DSCRIPTN 
 IF @NROORDCOL=19 SELECT @NOMCOL19=@DSCRIPTN 
 IF @NROORDCOL=20 SELECT @NOMCOL20=@DSCRIPTN 
 
 FETCH NEXT FROM HEADERS INTO @NROORDCOL,@DSCRIPTN 
     END 
CLOSE HEADERS 
DEALLOCATE HEADERS 
 
INSERT INTO AWLI50001 (USERID,RPTID,NOMCOL01,NOMCOL02,NOMCOL03,NOMCOL04,NOMCOL05,NOMCOL06,NOMCOL07,NOMCOL08,NOMCOL09,NOMCOL10,NOMCOL11,NOMCOL12,NOMCOL13,NOMCOL14,NOMCOL15,NOMCOL16,NOMCOL17,NOMCOL18,NOMCOL19,NOMCOL20) 
  VALUES  (@USERID,@IDReporte,@NOMCOL01,@NOMCOL02,@NOMCOL03,@NOMCOL04,@NOMCOL05,@NOMCOL06,@NOMCOL07,@NOMCOL08, @NOMCOL09,@NOMCOL10,@NOMCOL11,@NOMCOL12,@NOMCOL13,@NOMCOL14,@NOMCOL15,@NOMCOL16,@NOMCOL17,@NOMCOL18,@NOMCOL19,@NOMCOL20) 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[AWLI_ReporteImpuestos_LlenoHeaders] TO [DYNGRP] 
GO 

/*End_AWLI_ReporteImpuestos_LlenoHeaders*/
/*Begin_AWLI_ReporteImpuestos_SM*/
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[AWLI_ReporteImpuestos_SM]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[AWLI_ReporteImpuestos_SM]
GO

CREATE PROCEDURE AWLI_ReporteImpuestos_SM 
@IDReporte AS CHAR(15),
@USERID AS CHAR(15),
@COL_22 AS VARCHAR(15) = NULL 
AS

EXEC AWLI_ReporteImpuestos_LlenoHeaders @IDReporte,@USERID

DELETE FROM AWLI50003 WHERE RPTID=@IDReporte AND USERID=@USERID  

DECLARE @TipoReporte as SMALLINT, @HISTORY as TINYINT, @UNPSTTRX as TINYINT, @OPENTRX as TINYINT, @SORTBY1 as SMALLINT
DECLARE @AWFiltraXDocumentDate as TINYINT, @STTDOCDT as DATETIME, @ENDDOCDT as DATETIME, @AWFiltraXPostDate as TINYINT
DECLARE @STTPSTDT as DATETIME, @ENDPSTDT as DATETIME, @TipoCorteControl as smallint
DECLARE @RM_SALESINV as tinyint, @RM_DEBITMEM as tinyint, @RM_FINCHRGS as tinyint, @RM_SERVNREP as tinyint, @RM_WARRANTY as tinyint
DECLARE @RM_CREDMEMO as tinyint, @RM_RETURNS as tinyint, @PM_INVOICE as tinyint, @PM_FINCHR as tinyint, @PM_MISCHARG AS tinyint, @PM_RETURN as tinyint
DECLARE @PM_CRDMEM as tinyint, @FiltraSOPDOC as tinyint

SELECT @TipoReporte=TipoReporte, @HISTORY=HISTORY, @UNPSTTRX=UNPSTTRX, @OPENTRX=OpenTRX, @SORTBY1=SORTBY1, 
 @AWFiltraXDocumentDate=AWFiltraXDocumentDate, @STTDOCDT=STTDOCDT, @ENDDOCDT=ENDDOCDT,  @AWFiltraXPostDate=AWFiltraXPostDate, 
 @STTPSTDT=STTPSTDT, @ENDPSTDT=ENDPSTDT, @TipoCorteControl=TipoCorteControl,
 @RM_SALESINV=SALESINV, @RM_DEBITMEM=DEBITMEM, @RM_FINCHRGS=FINCHRGS, @RM_SERVNREP=SERVNREP, @RM_WARRANTY=WARRANTY,
 @RM_CREDMEMO=CREDMEMO, @RM_RETURNS=RETURNS, @PM_INVOICE=PMINVOIC, @PM_FINCHR=PMFINCHR, @PM_MISCHARG=MISCHARG,
 @PM_RETURN=PMRETURN, @PM_CRDMEM=PMCRDMEM, @FiltraSOPDOC=AWLI_Filtra_SOP_Doc
FROM AWLI40001 WHERE @IDReporte=RPTID

DECLARE @D_TYPE AS INT, @D_STATE AS VARCHAR(4), @D_DOCTYPE AS INT, @D_DOCNUMBR AS CHAR(21), @D_VCHRNMBR AS CHAR(21), @D_DOCDATE AS DATETIME
DECLARE @D_GLPOSTDT AS DATETIME, @D_CUSTVENDID AS CHAR(15), @D_CUSTVENDNAME AS CHAR(65), @D_TXRGNNUM AS CHAR(25)
DECLARE @D_SALESPURCHAMNT AS NUMERIC(19,5), @D_TRDISAMT AS NUMERIC(19,5), @D_FRTAMNT AS NUMERIC(19,5), @D_MISCAMNT AS NUMERIC(19,5)
DECLARE @D_TAXAMNT AS NUMERIC(19,5), @D_DOCAMNT AS NUMERIC(19,5), @D_VOIDED AS INT, @D_DOCID AS CHAR(15), @D_DOCTYPEDESC AS VARCHAR(7), @D_VOIDDATE AS DATETIME, @D_CURNCYID AS CHAR(15)

DECLARE @T_TYPE AS INT, @T_DOCTYPE AS INT, @T_VCHRNMBR AS CHAR(21), @T_TAXDTLID AS CHAR(15), @T_TAXAMNT AS NUMERIC(19,5)
DECLARE @T_TAXDTAMT AS NUMERIC(19,5), @T_TDTTXAMT AS NUMERIC(19,5)
DECLARE @NumeroDeOrden as SMALLINT, @IDGRUPOIMP as CHAR(15), @DESCGRUPOIMP AS CHAR(31)

DECLARE @COL01 AS NUMERIC(19,5), @COL02 AS NUMERIC(19,5), @COL03 AS NUMERIC(19,5), @COL04 AS NUMERIC(19,5), @COL05 AS NUMERIC(19,5)
DECLARE @COL06 AS NUMERIC(19,5), @COL07 AS NUMERIC(19,5), @COL08 AS NUMERIC(19,5), @COL09 AS NUMERIC(19,5), @COL10 AS NUMERIC(19,5)
DECLARE @COL11 AS NUMERIC(19,5), @COL12 AS NUMERIC(19,5), @COL13 AS NUMERIC(19,5), @COL14 AS NUMERIC(19,5), @COL15 AS NUMERIC(19,5)
DECLARE @COL16 AS NUMERIC(19,5), @COL17 AS NUMERIC(19,5), @COL18 AS NUMERIC(19,5), @COL19 AS NUMERIC(19,5), @COL20 AS NUMERIC(19,5)
DECLARE @MONTO AS NUMERIC(19,5), @OPERACION AS INTEGER
DECLARE @T_COL01 AS NUMERIC(19,5), @T_COL02 AS NUMERIC(19,5), @T_COL03 AS NUMERIC(19,5), @T_COL04 AS NUMERIC(19,5), @T_COL05 AS NUMERIC(19,5)
DECLARE @T_COL06 AS NUMERIC(19,5), @T_COL07 AS NUMERIC(19,5), @T_COL08 AS NUMERIC(19,5), @T_COL09 AS NUMERIC(19,5), @T_COL10 AS NUMERIC(19,5)
DECLARE @T_COL11 AS NUMERIC(19,5), @T_COL12 AS NUMERIC(19,5), @T_COL13 AS NUMERIC(19,5), @T_COL14 AS NUMERIC(19,5), @T_COL15 AS NUMERIC(19,5)
DECLARE @T_COL16 AS NUMERIC(19,5), @T_COL17 AS NUMERIC(19,5), @T_COL18 AS NUMERIC(19,5), @T_COL19 AS NUMERIC(19,5), @T_COL20 AS NUMERIC(19,5)
DECLARE @NROGRUPO AS SMALLINT, @IDGRUPO as CHAR(15), @DESCGRUPO AS CHAR(31)

DECLARE @COL_NROORDCOL AS INTEGER, @COL_TIPOIMP AS INTEGER, @COL_OPVTAX AS INTEGER, @COL_TAXDTLID AS CHAR(15)


 If @TipoReporte=1 AND @SORTBY1=1 
  DECLARE DOCUMENTOS CURSOR FOR SELECT * FROM AWLI_DOCUMENTOS_SM 
  WHERE  TYPE=1 AND  ((DOCTYPE=1 AND @PM_INVOICE=1) OR  (DOCTYPE=2 AND @PM_FINCHR=1) OR  (DOCTYPE=3 AND @PM_MISCHARG=1) OR 
      (DOCTYPE=4 AND @PM_RETURN=1) OR (DOCTYPE=5 AND @PM_CRDMEM=1))  AND ((STATE='WORK' AND @UNPSTTRX=1) OR 
      (STATE='OPEN' AND @OPENTRX=1) OR (STATE='HIST' AND @HISTORY=1)) AND (NOT @AWFiltraXDocumentDate=1 OR 
     (DOCDATE >=@STTDOCDT AND DOCDATE<=@ENDDOCDT)) AND (NOT @AWFiltraXPostDate=1 OR (GLPOSTDT >=@STTPSTDT AND 
     GLPOSTDT<=@ENDPSTDT))
  ORDER BY DOCDATE,DOCNUMBR 
 else If @TipoReporte=1 AND @SORTBY1=2  
  DECLARE DOCUMENTOS CURSOR FOR SELECT * FROM AWLI_DOCUMENTOS_SM 
  WHERE TYPE=1 AND ((DOCTYPE=1 AND @PM_INVOICE=1) OR (DOCTYPE=2 AND @PM_FINCHR=1) OR (DOCTYPE=3 AND @PM_MISCHARG=1) OR 
     (DOCTYPE=4 AND @PM_RETURN=1) OR (DOCTYPE=5 AND @PM_CRDMEM=1)) AND ((STATE='WORK' AND @UNPSTTRX=1) OR 
      (STATE='OPEN' AND @OPENTRX=1) OR (STATE='HIST' AND @HISTORY=1)) AND (NOT @AWFiltraXDocumentDate=1 OR 
     (DOCDATE >=@STTDOCDT AND DOCDATE<=@ENDDOCDT)) AND (NOT @AWFiltraXPostDate=1 OR (GLPOSTDT >=@STTPSTDT AND 
     GLPOSTDT<=@ENDPSTDT)) 
  ORDER BY DOCDATE,CUSTVENDID, DOCNUMBR 
 else if @TipoReporte=2 AND @SORTBY1=1   
  DECLARE DOCUMENTOS CURSOR FOR SELECT * FROM AWLI_DOCUMENTOS_SM 
  WHERE TYPE=2 AND ((DOCTYPE=1 AND @RM_SALESINV=1) OR (DOCTYPE=3 AND @RM_DEBITMEM=1) OR (DOCTYPE=4 AND @RM_FINCHRGS=1) OR 
     (DOCTYPE=5 AND @RM_SERVNREP=1) OR (DOCTYPE=6 AND @RM_WARRANTY=1) OR  (DOCTYPE=7 AND @RM_CREDMEMO=1) OR 
      (DOCTYPE=8 AND @RM_RETURNS=1) ) AND ((STATE='WORK' AND @UNPSTTRX=1) OR (STATE='OPEN' AND @OPENTRX=1) OR 
      (STATE='HIST' AND @HISTORY=1)) AND (NOT @AWFiltraXDocumentDate=1 OR (DOCDATE >=@STTDOCDT AND DOCDATE<=@ENDDOCDT)) AND 
     (NOT @AWFiltraXPostDate=1 OR (GLPOSTDT >=@STTPSTDT AND GLPOSTDT<=@ENDPSTDT)) AND ((DOCID = '') OR 
      NOT EXISTS  (SELECT  *  FROM AWLI40003  WHERE  AWLI_DOCUMENTOS_SM.DOCID = AWLI40003.DOCID AND RPTID = @IDReporte) OR 
     NOT (@FiltraSOPDOC = 1)) 
  ORDER BY DOCDATE,DOCNUMBR 
 else if @TipoReporte=2 AND @SORTBY1=2   
  DECLARE DOCUMENTOS CURSOR FOR SELECT * FROM AWLI_DOCUMENTOS_SM 
  WHERE TYPE=2 AND ((DOCTYPE=1 AND @RM_SALESINV=1) OR (DOCTYPE=3 AND @RM_DEBITMEM=1) OR (DOCTYPE=4 AND @RM_FINCHRGS=1) OR 
      (DOCTYPE=5 AND @RM_SERVNREP=1) OR (DOCTYPE=6 AND @RM_WARRANTY=1) OR (DOCTYPE=7 AND @RM_CREDMEMO=1) OR 
      (DOCTYPE=8 AND @RM_RETURNS=1) ) AND ((STATE='WORK' AND @UNPSTTRX=1) OR (STATE='OPEN' AND @OPENTRX=1) OR 
      (STATE='HIST' AND @HISTORY=1)) AND (NOT @AWFiltraXDocumentDate=1 OR (DOCDATE >=@STTDOCDT AND DOCDATE<=@ENDDOCDT)) AND 
     (NOT @AWFiltraXPostDate=1 OR (GLPOSTDT >=@STTPSTDT AND GLPOSTDT<=@ENDPSTDT)) AND ((DOCID = '') OR 
     NOT EXISTS  (SELECT  *  FROM AWLI40003  WHERE  AWLI_DOCUMENTOS_SM.DOCID = AWLI40003.DOCID AND RPTID = @IDReporte) OR 
     NOT (@FiltraSOPDOC = 1)) 
  ORDER BY DOCDATE,CUSTVENDID, DOCNUMBR 
 else return 
 

 OPEN  DOCUMENTOS
 FETCH NEXT FROM DOCUMENTOS INTO @D_TYPE, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, @D_DOCDATE,@D_GLPOSTDT, @D_CUSTVENDID,
       @D_CUSTVENDNAME,  @D_TXRGNNUM, @D_SALESPURCHAMNT, @D_TRDISAMT, @D_FRTAMNT, @D_MISCAMNT, @D_TAXAMNT,
      @D_DOCAMNT, @D_VOIDED, @D_DOCID, @D_DOCTYPEDESC, @D_VOIDDATE, @D_CURNCYID


 WHILE (@@FETCH_STATUS=0)    
      BEGIN 
  
   SELECT @COL01=0, @COL02=0, @COL03=0, @COL04=0, @COL05=0, @COL06=0, @COL07=0, @COL08=0, @COL09=0, @COL10=0, @COL11=0, @COL12=0, @COL13=0, @COL14=0, @COL15=0, @COL16=0, @COL17=0, @COL18=0, @COL19=0, @COL20=0
  
   EXEC AWLI_ReporteImpuestos_AcumuloColumnaTotales @IDReporte,@USERID,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT,
          @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08,@COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20,
          @COL01 OUTPUT,@COL02 OUTPUT,@COL03 OUTPUT,@COL04 OUTPUT,@COL05 OUTPUT,@COL06 OUTPUT,@COL07 OUTPUT,@COL08 OUTPUT,
          @COL09 OUTPUT,@COL10 OUTPUT,@COL11 OUTPUT,@COL12 OUTPUT,@COL13 OUTPUT,@COL14 OUTPUT,@COL15 OUTPUT, 
          @COL16 OUTPUT,@COL17 OUTPUT,@COL18 OUTPUT,@COL19 OUTPUT,@COL20 OUTPUT 
  
   
    DECLARE DOC_IMPUESTOS CURSOR FOR 
    SELECT    AWLI_IMPUESTOS_SM.*, ISNULL(GRUPOIMP.NumeroDeOrden, 0) AS NumeroDeOrden, ISNULL(GRUPOIMP.IDGRIMP, '')  AS IDGRUPOIMP, ISNULL(GRUPOIMP.DSCRIPTN, '') AS DSCRIPTN 
    FROM        AWLI_IMPUESTOS_SM LEFT OUTER JOIN 
                              (SELECT     AWLI40202.TAXDTLID, AWLI40002.RPTID, AWLI40002.NumeroDeOrden, AWLI40202.IDGRIMP, AWLI40002.DSCRIPTN 
                                FROM          AWLI40002 INNER JOIN 
                                                       AWLI40202 ON AWLI40002.IDGRIMP = AWLI40202.IDGRIMP 
                                WHERE      (AWLI40002.RPTID = @IDReporte)) GRUPOIMP ON GRUPOIMP.TAXDTLID = dbo.AWLI_IMPUESTOS_SM.TAXDTLID 
    WHERE     (TYPE=@D_TYPE AND DOCTYPE=@D_DOCTYPE AND VCHRNMBR=@D_VCHRNMBR) AND 
       
      (  NOT EXISTS  (SELECT     TipoCorteControl FROM AWLI40001 WHERE      AWLI40001.RPTID = @IDReporte AND TipoCorteControl = 2) OR 
     NOT  (GRUPOIMP.NumeroDeOrden IS NULL)  ) 
    ORDER BY GRUPOIMP.NumeroDeOrden, dbo.AWLI_IMPUESTOS_SM.TAXDTLID 
    OPEN DOC_IMPUESTOS
   
    FETCH NEXT FROM DOC_IMPUESTOS INTO @T_TYPE, @T_DOCTYPE, @T_VCHRNMBR, @T_TAXDTLID, @T_TAXAMNT, @T_TAXDTAMT,
          @T_TDTTXAMT, @NumeroDeOrden, @IDGRUPOIMP,@DESCGRUPOIMP 
   
    IF @TipoCorteControl=1
         BEGIN select @NumeroDeOrden=0, @IDGRUPOIMP='', @DESCGRUPOIMP='' END
   
    IF (@@FETCH_STATUS=0)     
         BEGIN 
     
      SELECT @NROGRUPO=@NumeroDeOrden, @IDGRUPO= @IDGRUPOIMP, @DESCGRUPO=@DESCGRUPOIMP
      SELECT @T_COL01=@COL01, @T_COL02=@COL02, @T_COL03=@COL03, @T_COL04=@COL04, @T_COL05=@COL05, @T_COL06=@COL06, @T_COL07=@COL07, @T_COL08=@COL08,
        @T_COL09=@COL09, @T_COL10=@COL10, @T_COL11=@COL11, @T_COL12=@COL12, @T_COL13=@COL13, @T_COL14=@COL14, @T_COL15=@COL15, 
        @T_COL16=@COL16, @T_COL17=@COL17, @T_COL18=@COL18, @T_COL19=@COL19, @T_COL20=@COL20 
     
      WHILE (@@FETCH_STATUS=0)
           BEGIN  
       
        EXEC AWLI_ReporteImpuestos_AcumuloColumnaImpuestos @IDReporte, @USERID, @T_TAXDTLID, @T_TAXAMNT,@T_TAXDTAMT,@T_TDTTXAMT, @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,
               @T_COL08,@T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,
               @T_COL01 OUTPUT,@T_COL02 OUTPUT,@T_COL03 OUTPUT,@T_COL04 OUTPUT,@T_COL05 OUTPUT,@T_COL06 OUTPUT,@T_COL07 OUTPUT,@T_COL08 OUTPUT,
               @T_COL09 OUTPUT,@T_COL10 OUTPUT,@T_COL11 OUTPUT,@T_COL12 OUTPUT,@T_COL13 OUTPUT,@T_COL14 OUTPUT,@T_COL15 OUTPUT,@T_COL16 OUTPUT,@T_COL17 OUTPUT,@T_COL18 OUTPUT,@T_COL19 OUTPUT,@T_COL20 OUTPUT
       
        FETCH NEXT FROM DOC_IMPUESTOS INTO @T_TYPE, @T_DOCTYPE, @T_VCHRNMBR, @T_TAXDTLID, @T_TAXAMNT, @T_TAXDTAMT, @T_TDTTXAMT, @NumeroDeOrden, @IDGRUPOIMP,@DESCGRUPOIMP
       
        IF @TipoCorteControl=1 
             BEGIN  
         select @NumeroDeOrden=0, @IDGRUPOIMP='', @DESCGRUPOIMP='' 
             END 
       
        IF (@@FETCH_STATUS=0)
             BEGIN 
         IF @NROGRUPO<>@NumeroDeOrden  
              BEGIN 
          IF (@D_TYPE=1 AND (@D_DOCTYPE=4 OR @D_DOCTYPE=5)) OR (@D_TYPE=2 AND (@D_DOCTYPE=7 OR @D_DOCTYPE=8)) 
               BEGIN   EXEC AWLI_ReporteImpuestos_InserAWLI50003 
            @IDReporte, @USERID, @D_TYPE, @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, 
            @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
            @D_VOIDDATE,@D_CURNCYID,-1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
            @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,@T_COL08, @T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,@COL_22   END
          ELSE 
                BEGIN  EXEC AWLI_ReporteImpuestos_InserAWLI50003 
            @IDReporte, @USERID, @D_TYPE, @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, 
            @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
            @D_VOIDDATE,@D_CURNCYID,1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
            @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,@T_COL08, @T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,@COL_22  END 
          
          SELECT @NROGRUPO=@NumeroDeOrden, @IDGRUPO= @IDGRUPOIMP, @DESCGRUPO=@DESCGRUPOIMP 
          SELECT @T_COL01=@COL01, @T_COL02=@COL02, @T_COL03=@COL03, @T_COL04=@COL04, @T_COL05=@COL05, @T_COL06=@COL06, @T_COL07=@COL07, @T_COL08=@COL08, 
            @T_COL09=@COL09, @T_COL10=@COL10, @T_COL11=@COL11, @T_COL12=@COL12, @T_COL13=@COL13, @T_COL14=@COL14, @T_COL15=@COL15, @T_COL16=@COL16, @T_COL17=@COL17, @T_COL18=@COL18, @T_COL19=@COL19, @T_COL20=@COL20 
              END 
             END  
        ELSE   
             BEGIN 
         IF (@D_TYPE=1 AND (@D_DOCTYPE=4 OR @D_DOCTYPE=5)) OR (@D_TYPE=2 AND (@D_DOCTYPE=7 OR @D_DOCTYPE=8)) 
              BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003 
           @IDReporte, @USERID, @D_TYPE, @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, 
           @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
           @D_VOIDDATE,@D_CURNCYID,-1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
           @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,@T_COL08, @T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,@COL_22  END 
         ELSE 
              BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
           @IDReporte, @USERID, @D_TYPE, @NROGRUPO, @IDGRUPO, @DESCGRUPO, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
           @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
           @D_VOIDDATE,@D_CURNCYID,1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
           @T_COL01,@T_COL02,@T_COL03,@T_COL04,@T_COL05,@T_COL06,@T_COL07,@T_COL08, @T_COL09,@T_COL10,@T_COL11,@T_COL12,@T_COL13,@T_COL14,@T_COL15,@T_COL16,@T_COL17,@T_COL18,@T_COL19,@T_COL20,@COL_22  END 
             END 
           END     
         END 
    ELSE         
         BEGIN 
     IF @TipoCorteControl=1   
          BEGIN 
      IF (@D_TYPE=1 AND (@D_DOCTYPE=4 OR @D_DOCTYPE=5)) OR (@D_TYPE=2 AND (@D_DOCTYPE=7 OR @D_DOCTYPE=8)) 
           BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
        @IDReporte, @USERID, @D_TYPE, 0, '', '', @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
        @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
        @D_VOIDDATE,@D_CURNCYID,-1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
        @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08, @COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20,@COL_22  END 
      ELSE 
           BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
        @IDReporte, @USERID, @D_TYPE, 0, '', '', @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
        @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
        @D_VOIDDATE,@D_CURNCYID,1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
        @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08, @COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20,@COL_22  END 
          END 
     ELSE IF @TipoCorteControl=2   
          BEGIN 
      DECLARE CORTE_CONTROL CURSOR FOR 
      SELECT NumeroDeOrden, IDGRIMP,DSCRIPTN FROM AWLI40002  
      WHERE RPTID=@IDReporte AND INCZERO=1 
      ORDER BY NumeroDeOrden, IDGRIMP 
      OPEN CORTE_CONTROL 
      FETCH NEXT FROM CORTE_CONTROL INTO @NumeroDeOrden, @IDGRUPOIMP,@DESCGRUPO 
      IF (@@FETCH_STATUS<>0) 
           BEGIN SELECT @NumeroDeOrden=0, @IDGRUPO= '', @DESCGRUPO='' END 
      CLOSE CORTE_CONTROL 
      DEALLOCATE CORTE_CONTROL 
      IF (@D_TYPE=1 AND (@D_DOCTYPE=4 OR @D_DOCTYPE=5)) OR (@D_TYPE=2 AND (@D_DOCTYPE=7 OR @D_DOCTYPE=8)) 
           BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
        @IDReporte, @USERID, @D_TYPE, 0, '', '', @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
        @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
        @D_VOIDDATE,@D_CURNCYID,-1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
        @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08, @COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20,@COL_22  END 
      ELSE 
           BEGIN EXEC AWLI_ReporteImpuestos_InserAWLI50003  
        @IDReporte, @USERID, @D_TYPE, 0, '', '', @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR,  
        @D_DOCDATE, @D_GLPOSTDT, @D_CUSTVENDID, @D_CUSTVENDNAME, @D_TXRGNNUM, @D_VOIDED, @D_DOCID,@D_DOCTYPEDESC, 
        @D_VOIDDATE,@D_CURNCYID,1,@D_SALESPURCHAMNT,@D_TRDISAMT,@D_FRTAMNT,@D_MISCAMNT,@D_TAXAMNT,@D_DOCAMNT, 
        @COL01,@COL02,@COL03,@COL04,@COL05,@COL06,@COL07,@COL08, @COL09,@COL10,@COL11,@COL12,@COL13,@COL14,@COL15,@COL16,@COL17,@COL18,@COL19,@COL20,@COL_22  END 
          END 
         END 
    
    CLOSE  DOC_IMPUESTOS 
    DEALLOCATE DOC_IMPUESTOS 
    
   FETCH NEXT FROM DOCUMENTOS INTO @D_TYPE, @D_STATE, @D_DOCTYPE, @D_DOCNUMBR, @D_VCHRNMBR, @D_DOCDATE, @D_GLPOSTDT,@D_CUSTVENDID, @D_CUSTVENDNAME,   
           @D_TXRGNNUM, @D_SALESPURCHAMNT, @D_TRDISAMT, @D_FRTAMNT, @D_MISCAMNT, @D_TAXAMNT, @D_DOCAMNT, @D_VOIDED, @D_DOCID, @D_DOCTYPEDESC, @D_VOIDDATE,@D_CURNCYID 
      END    
  
 
 CLOSE DOCUMENTOS 
 DEALLOCATE DOCUMENTOS 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[AWLI_ReporteImpuestos_SM] TO [DYNGRP] 
GO 

/*End_AWLI_ReporteImpuestos_SM*/
