USE [PRO12]
GO

/****** Object:  View [dbo].[GXPR_FC_ELECTRONICA]    Script Date: 16/08/2018 11:53:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO












CREATE VIEW  [dbo].[GXPR_FC_ELECTRONICA] AS
 SELECT --    TOP 100 PERCENT 
      --Datos Compañia Emite
       rtrim(CMP.CMPNYNAM) CMPNYNAM --OK
      ,rtrim(concat(rtrim(CMP.ADDRESS1),rtrim(CMP.ADDRESS2),rtrim(CMP.ADDRESS3),' - ',rtrim(CMP.CITY),' - ', rtrim(CMP.STATE))) CMPADRESS  --OK
	  ,'file:'+ ARC.fileName FileName --OK
	  ,Substring(TAXREGTN,1,2) + '-' + Substring(TAXREGTN,3,8) + '-' + Substring(TAXREGTN,11,1)	CUIT --OK Falta separar
	  ,Substring(INFO.INETINFO,charindex('IIBB=',INFO.INETINFO,1)+5,11) IIBB -- OK
	  ,Substring(INFO.INETINFO,charindex('FECHA_INICIO=',INFO.INETINFO,1)+13,10) FECHA_INICIO --OK
	  ,Substring(INFO.INETINFO,charindex('COND_IVA=',INFO.INETINFO,1)+9,50) COND_IVA --NOK
	  ,rtrim(FEI_COD) FEI_COD --OK
      ,rtrim(FEI_LETRA1) FEI_LETRA1 --OK
      ,rtrim(FEI_PDV) FEI_PDV --OK
      ,FEI_NRO --NOK
      ,FEI_CAE --NOK
      ,FORMAT(FEI_CAE_DUE,'dd-MM-yyyy') FEI_CAE_DUE --OK
	  ,rtrim(FORMAT(FEI.FEI_PeriodoDesde,'dd-MM-yyyy')) PERIODO_DESDE
	  ,rtrim(FORMAT(FEI.FEI_PeriodoHasta,'dd-MM-yyyy')) PERIODO_HASTA
	  ,rtrim(FORMAT(FEI.FEI_VtoPago	  ,'dd-MM-yyyy'))  VTO_PAGO	
	  ,rtrim(SUBSTRING (TAXREGTN,1,11))+rtrim(FEI_COD)+rtrim(FEI_PDV)+rtrim(FEI_CAE)+rtrim(FORMAT(FEI_CAE_DUE,'yyyyMMdd')) CODIGO_BARRA --OK
	  -- Datos FACnte Factura Cabecera
	  ,rtrim(FAC.SOPNUMBE) NRO_FACTURA --OK
	  ,rtrim(FAC.SOPTYPE) TIPO_FACTURA --OK
	  ,substring(FAC.DOCID,1,2) DOCID
	  ,rtrim(FORMAT(FAC.DOCDATE,'dd-MM-yyyy')) FECHA --OK
	  ,FAC.[PYMTRMID] COND_PAGO --OK
	  ,FAC.[CUSTNMBR] ID_FACNTE --OK
	  ,FAC.[CUSTNAME] NOMBRE_CLIENTE --OK
   	  ,FAC.[CSTPONBR] NRO_ORDEN --OK
   	  ,rtrim(concat(rtrim(DIR.ADDRESS1),rtrim(DIR.ADDRESS2),rtrim(DIR.ADDRESS3),' - ',rtrim(DIR.CITY),' - ', rtrim(DIR.STATE))) CLNT_ADRESS --OK
	  -- DAtos FACnte Factura
	  ,rtrim(FAC.CURNCYID ) CURNCYID
	  ,XCHGRATE
	  ,FAC.TRDISAMT  --OK
      ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN FAC.DOCAMNT 
	                                    ELSE FAC.SUBTOTAL
										END SUBTOTAL --OK
      ,Substring(FAC.TXRGNNUM,1,2) + '-' + Substring(FAC.TXRGNNUM,3,8) + '-' + Substring(FAC.TXRGNNUM,11,1)	CLNT_CUIT --OK
      ,FAC.TAXAMNT  IMPUESTO_DISCR --OK
      ,FAC.BCKTXAMT IMPUESTO_INCL --OK
      ,FAC.DOCAMNT  IMPORTE_TOTAL --OK
	  ,FAC.DOCAMNT  IMPORTE_FUNCIONAL --OK
	  ,IVA.RESPBLE CLNT_IVA --OK
	  ,rtrim(FORMAT(FAC.DUEDATE,'dd-MM-yyyy')) DUEDATE
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-27%') END IMP_IVA_27 
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-21%') END IMP_IVA_21 --NOK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-10%') END IMP_IVA_10 --NOK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-05%') END IMP_IVA_05 --NOK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-02%')    END IMP_IVA_02 --NOK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-00%') END IMP_IVA_00 --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'P-IV%')    PERC_IVA      --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'P-IB%')    PERC_IIBB     --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-RETGAN%') RET_GANAN     --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IMPINT%') IMP_INTERNO   --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IMPMUN%') IMP_MUNICIPAL --NOK
	  -- Detalles Factura
      ,rtrim([ITEMNMBR]) ITEMNMBR  --OK
      ,RTRIM(ITEMDESC) ITEMDESC --OK
      ,[UOFM]      --OK
      ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN [UNITPRCE] + (DET.[TAXAMNT]/QUANTITY)
										ELSE [UNITPRCE] 
										END UNITPRCE --OK
      ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN [XTNDPRCE] + DET.[TAXAMNT]
										ELSE [XTNDPRCE]
										END XTNDPRCE --OK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN  0
										ELSE DET.[TAXAMNT] --OK
										END TAXAMNT
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN  NULL 
										ELSE dbo.GXPRFuncGetTaxItm(DET.SOPTYPE,DET.SOPNUMBE,DET.LNITMSEQ) 
										END PORC_IVA
      ,DET.[MRKDNAMT] --OK 
      ,QUANTITY QUANTITY--OK
	  ,rtrim(CSTPONBR) NRO_REMITO
From DYNAMICS.dbo.SY01500    AS CMP
     INNER JOIN DYNAMICS.dbo.SY01501 AS ARC ON ARC.CMPANYID = CMP.CMPANYID
	 LEFT OUTER JOIN SY01200 AS INFO ON CMP.INTERID = INFO.MASTER_ID,
	 SOP10100                AS FAC 
	 INNER JOIN SOP10200     AS DET ON FAC.SOPTYPE	= DET.SOPTYPE AND FAC.SOPNUMBE  = DET.SOPNUMBE
	 INNER JOIN RM00102      AS DIR ON FAC.CUSTNMBR	= DIR.CUSTNMBR AND FAC.PRBTADCD = DIR.ADRSCODE
	 LEFT OUTER JOIN FEI_SOP30200 AS FEI ON FAC.SOPTYPE	= FEI.SOPTYPE AND FAC.SOPNUMBE  = FEI.SOPNUMBE
	 LEFT OUTER JOIN AWLI_RM00101 AS RM ON FAC.CUSTNMBR = RM.CUSTNMBR 
	 LEFT OUTER JOIN DYNAMICS.dbo.AWLI40330 AS IVA ON RM.RESP_TYPE = IVA.RESP_TYPE
	 LEFT OUTER JOIN SOP10105 IMP ON DET.SOPTYPE	= IMP.SOPTYPE AND DET.SOPNUMBE  = IMP.SOPNUMBE AND DET.LNITMSEQ = IMP.LNITMSEQ AND  IMP.TAXDTLID LIKE '%'+ rtrim('V-IV-')+'%'
WHERE  CMP.INTERID = DB_NAME()
  AND  INFO.ADRSCODE = 'FC_ELECTRONICA' 
  AND  INFO.MASTER_TYPE = 'CMP'
UNION ALL
SELECT --    TOP 100 PERCENT 
      --Datos Compañia Emite
         rtrim(CMP.CMPNYNAM) CMPNYNAM --OK
      ,rtrim(concat(rtrim(CMP.ADDRESS1),rtrim(CMP.ADDRESS2),rtrim(CMP.ADDRESS3),' - ',rtrim(CMP.CITY),' - ', rtrim(CMP.STATE))) CMPADRESS  --OK
	  ,'file:'+ ARC.fileName FileName --OK
	  ,Substring(TAXREGTN,1,2) + '-' + Substring(TAXREGTN,3,8) + '-' + Substring(TAXREGTN,11,1)	CUIT --OK Falta separar
	  ,Substring(INFO.INETINFO,charindex('IIBB=',INFO.INETINFO,1)+5,11) IIBB -- OK
	  ,Substring(INFO.INETINFO,charindex('FECHA_INICIO=',INFO.INETINFO,1)+13,10) FECHA_INICIO --OK
	  ,Substring(INFO.INETINFO,charindex('COND_IVA=',INFO.INETINFO,1)+9,50) COND_IVA --NOK
	  ,rtrim(FEI_COD) FEI_COD --OK
      ,rtrim(FEI_LETRA1) FEI_LETRA1 --OK
      ,rtrim(FEI_PDV) FEI_PDV --OK
      ,FEI_NRO --NOK
      ,FEI_CAE --NOK
      ,FORMAT(FEI_CAE_DUE,'dd-MM-yyyy') FEI_CAE_DUE --OK
	  ,rtrim(FORMAT(FEI.FEI_PeriodoDesde,'dd-MM-yyyy')) PERIODO_DESDE
	  ,rtrim(FORMAT(FEI.FEI_PeriodoHasta,'dd-MM-yyyy')) PERIODO_HASTA
	  ,rtrim(FORMAT(FEI.FEI_VtoPago	  ,'dd-MM-yyyy'))  VTO_PAGO	
	  ,rtrim(SUBSTRING (TAXREGTN,1,11))+rtrim(FEI_COD)+rtrim(FEI_PDV)+rtrim(FEI_CAE)+rtrim(FORMAT(FEI_CAE_DUE,'yyyyMMdd')) CODIGO_BARRA --OK
	  --,rtrim(SUBSTRING (TAXREGTN,1,11)) codigo_barra+
	  -- Datos FACnte Factura Cabecera
	  ,rtrim(FAC.SOPNUMBE) NRO_FACTURA --OK
	  ,rtrim(FAC.SOPTYPE) TIPO_FACTURA --OK
	  ,substring(FAC.DOCID,1,2) DOCID
	  ,rtrim(FORMAT(FAC.DOCDATE,'dd-MM-yyyy')) FECHA --OK
	  ,FAC.[PYMTRMID] COND_PAGO --OK
	  ,FAC.[CUSTNMBR] ID_FACNTE --OK
	  ,FAC.[CUSTNAME] NOMBRE_CLIENTE --OK
   	  ,FAC.[CSTPONBR] NRO_ORDEN --OK
   	  ,rtrim(concat(rtrim(DIR.ADDRESS1),rtrim(DIR.ADDRESS2),rtrim(DIR.ADDRESS3),' - ',rtrim(DIR.CITY),' - ', rtrim(DIR.STATE))) CLNT_ADRESS --OK
	  -- DAtos FACnte Factura
	  ,rtrim(FAC.CURNCYID ) CURNCYID
	  ,XCHGRATE
	  ,FAC.TRDISAMT  --OK
      ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN FAC.DOCAMNT 
	                                    ELSE FAC.SUBTOTAL
										END SUBTOTAL --OK
      ,Substring(FAC.TXRGNNUM,1,2) + '-' + Substring(FAC.TXRGNNUM,3,8) + '-' + Substring(FAC.TXRGNNUM,11,1)	CLNT_CUIT --OK
      ,FAC.TAXAMNT IMPUESTO_DISCR --OK
      ,FAC.BCKTXAMT IMPUESTO_INCL --OK
      ,FAC.DOCAMNT  IMPORTE_TOTAL --OK
	  ,FAC.DOCAMNT  IMPORTE_FUNCIONAL --OK
	  ,IVA.RESPBLE CLNT_IVA --OK
	  ,rtrim(FORMAT(FAC.DUEDATE,'dd-MM-yyyy')) DUEDATE
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-27%') END IMP_IVA_27 
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-21%') END IMP_IVA_21 --NOK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-10%') END IMP_IVA_10 --NOK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-05%') END IMP_IVA_05 --NOK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-02%')    END IMP_IVA_02 --NOK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B' THEN NULL ELSE dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IV%-00%') END IMP_IVA_00 --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'P-IV%')    PERC_IVA      --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'P-IB%')    PERC_IIBB     --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-RETGAN%') RET_GANAN     --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IMPINT%') IMP_INTERNO   --NOK
	  ,dbo.GXPRFuncGetTax(FAC.SOPTYPE,FAC.SOPNUMBE,'V-IMPMUN%') IMP_MUNICIPAL --NOK
	  -- Detalles Factura
      ,rtrim([ITEMNMBR]) ITEMNMBR
      ,rtrim(ITEMDESC) ITEMDESC --OK
      ,[UOFM]      --OK
      ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN [UNITPRCE] + (DET.[TAXAMNT]/QUANTITY)
										ELSE [UNITPRCE] 
										END UNITPRCE --OK
      ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN [XTNDPRCE] + DET.[TAXAMNT]
										ELSE [XTNDPRCE]
										END XTNDPRCE --OK
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN  0
										ELSE DET.[TAXAMNT] --OK
										END TAXAMNT
	  ,CASE rtrim(FEI_LETRA1) WHEN 'B'	THEN  NULL 
										ELSE dbo.GXPRFuncGetTaxItm(DET.SOPTYPE,DET.SOPNUMBE,DET.LNITMSEQ) 
										END PORC_IVA
      ,DET.[MRKDNAMT] --OK 
	  ,QUANTITY QUANTITY --OK
	  ,rtrim(CSTPONBR) NRO_REMITO
From DYNAMICS.dbo.SY01500    AS CMP
     INNER JOIN DYNAMICS.dbo.SY01501 AS ARC ON ARC.CMPANYID = CMP.CMPANYID
	 LEFT OUTER JOIN SY01200 AS INFO ON CMP.INTERID = INFO.MASTER_ID,
	 SOP30200                AS FAC
	 INNER JOIN SOP30300     AS DET ON FAC.SOPTYPE	= DET.SOPTYPE AND FAC.SOPNUMBE  = DET.SOPNUMBE
	 INNER JOIN RM00102      AS DIR ON FAC.CUSTNMBR	= DIR.CUSTNMBR AND FAC.PRBTADCD = DIR.ADRSCODE
	 LEFT OUTER JOIN FEI_SOP30200 AS FEI ON FAC.SOPTYPE	= FEI.SOPTYPE AND FAC.SOPNUMBE  = FEI.SOPNUMBE
	 LEFT OUTER JOIN AWLI_RM00101 AS RM ON FAC.CUSTNMBR = RM.CUSTNMBR 
	 LEFT OUTER JOIN DYNAMICS.dbo.AWLI40330 AS IVA ON RM.RESP_TYPE = IVA.RESP_TYPE
WHERE  CMP.INTERID = DB_NAME()
  AND  INFO.ADRSCODE = 'FC_ELECTRONICA' 
  AND  INFO.MASTER_TYPE = 'CMP'
GO


