/****** Object:  User Defined Function dbo.fncESNUMERICO    Script Date: 14/6/2015 12:35:09 PM ******/
CREATE FUNCTION [dbo].[fncESNUMERICO] (	@DATO								VARCHAR(30)			
)
RETURNS TINYINT
AS
BEGIN
	DECLARE @INDICE tinyint
	DECLARE @RESULTADO TINYINT 

	SELECT @RESULTADO = 1

	SELECT @INDICE = 1
	WHILE @INDICE <= LEN(RTRIM(@DATO))
	BEGIN
		IF SUBSTRING(RTRIM(@DATO), @INDICE, 1) NOT BETWEEN '0' AND '9'
		BEGIN
			SELECT @INDICE = LEN(RTRIM(@DATO)) + 1
			SELECT @RESULTADO = 0
		END
		ELSE
		BEGIN
			SELECT @INDICE = @INDICE + 1
		END
	END
	RETURN ( @RESULTADO )
END




